apiVersion: v2
name: cell-wrapper-config
description: Accelleran's cell-wrapper config helm chart
type: application
version: 0.5.1
# renovate: image=accelleran/ncclient
appVersion: "0.2.0"
dependencies:
  - name: common
    version: 0.3.10
    repository: https://accelleran.github.io/helm-charts/
