apiVersion: v2
appVersion: 6.5.3
dependencies:
- condition: acc-kafka.enabled
  name: acc-kafka
  repository: https://accelleran.github.io/helm-charts/
  version: 0.3.1
- condition: acc-kminion.enabled
  name: acc-kminion
  repository: https://accelleran.github.io/helm-charts/
  version: 1.5.0
- condition: acc-sys-dashboard.enabled
  name: acc-sys-dashboard
  repository: https://accelleran.github.io/helm-charts/
  version: 3.4.16
- condition: dash-front-back-end.enabled
  name: dash-front-back-end
  repository: https://accelleran.github.io/helm-charts/
  version: 4.5.1
- name: loki-stack
  repository: https://accelleran.github.io/helm-charts/
  version: 0.43.0
- condition: acc-service-monitor.enabled
  name: acc-service-monitor
  repository: https://accelleran.github.io/helm-charts/
  version: 0.7.0
- condition: acc-service-orchestrator.enabled
  name: acc-service-orchestrator
  repository: https://accelleran.github.io/helm-charts/
  version: 2.5.0
- condition: global.enable4G
  name: acc-state-db
  repository: https://accelleran.github.io/helm-charts/
  version: 0.14.5
- condition: influxdb.enabled
  name: influxdb
  repository: https://accelleran.github.io/helm-charts/
  version: 5.0.2
- condition: vector.enabled
  name: vector
  repository: https://accelleran.github.io/helm-charts/
  version: 0.7.0
- condition: vectorfiveg.enabled
  name: vectorfiveg
  repository: https://accelleran.github.io/helm-charts/
  version: 0.6.1
- condition: acc-fiveg-pmcounters.enabled
  name: acc-fiveg-pmcounters
  repository: https://accelleran.github.io/helm-charts/
  version: 1.0.3
- condition: global.enable5G
  name: acc-5g-infrastructure
  repository: https://accelleran.github.io/5g-helm-charts
  version: 3.0.0
- alias: golang-nkafka-4g
  condition: global.enable4G
  name: golang-nkafka
  repository: https://accelleran.github.io/helm-charts/
  version: 1.2.1
- alias: golang-nkafka-5g
  condition: global.enable5G
  name: golang-nkafka
  repository: https://accelleran.github.io/helm-charts
  version: 1.2.1
- condition: global.enable4G
  name: acc-4g-infrastructure
  repository: https://accelleran.github.io/helm-charts/
  version: 5.1.0
- condition: ingress.enabled
  name: keycloak-ingress
  repository: https://accelleran.github.io/helm-charts/
  version: 0.1.0
- condition: config-api.enabled
  name: config-api
  repository: https://accelleran.github.io/helm-charts/
  version: 1.1.12
- condition: network-state-monitor.enabled
  name: network-state-monitor
  repository: https://accelleran.github.io/helm-charts/
  version: 0.1.0
- condition: cell-wrapper.enabled
  name: cell-wrapper
  repository: https://accelleran.github.io/helm-charts/
  version: 2.3.2
- condition: e2t.enabled
  name: e2t
  repository: https://accelleran.github.io/helm-charts/
  version: 1.0.0
# The ric chart is deprecated in favor of drax.
deprecated: true
description: DEPRECATED A Helm chart for Kubernetes
name: ric
type: application
version: 6.5.4
