{{- $values := index $.Values "netconf" -}}
{{- if ($values.initEditConfig).config -}}
{{- include
      "accelleran.common.configMap"
      (fromYaml (include "accelleran.cell-wrapper.netconf.init.configMap.args" .))
-}}
{{- end -}}


{{- define "accelleran.cell-wrapper.netconf.init.configMap.args" -}}
{{- $ := . -}}
{{- $values := index $.Values "netconf" -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ $values | toYaml | nindent 2 }}

name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) }}-init-rpcs
data:
  {{- range $index, $configRpc := $values.initEditConfig.config }}
  {{- $configRpc = tpl $configRpc $ -}}
  {{- if $configRpc }}
  init-edit-config-{{- $index -}}.xml: |
    {{- $configRpc | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}
