{{- range $job := $.Values.jobs }}
---
{{ include
      "accelleran.common.cronjob"
      (fromYaml (include "accelleran.cell-wrapper.netconf.cronjob.args" (list $ $job)))
}}
{{- end -}}


{{- define "accelleran.cell-wrapper.netconf.cronjob.args" -}}
{{- $ := first . -}}
{{- $values := $.Values.netconf -}}

{{- $job := index . 1 -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ (mergeOverwrite (deepCopy $values) (fromYaml (include "accelleran.cell-wrapper.netconf.cronjob.valueOverrides" (list $ $job)))) | toYaml | nindent 2 }}

name: "{{ $.Release.Name }}-{{ $job.name }}"
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 0 # will be restarted anyway

envFrom:
  - secretRef:
      name: {{ include "accelleran.cell-wrapper.netconf.secret.authentication.name" $ }}

volumes:
  - name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) }}-cron-rpcs
    configMap:
      name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) }}-cron-rpcs
      defaultMode: 0777

volumeMounts:
  - name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) }}-cron-rpcs
    mountPath: /rpcs
{{- end }}


{{- define "accelleran.cell-wrapper.netconf.cronjob.valueOverrides" -}}
{{- $ := first . -}}
{{- $values := $.Values.netconf -}}

{{- $job := index . 1 -}}

schedule: {{ $job.schedule | quote }}

containerName: netconf-cron-config
args:
  - "--host"
  - {{ include "accelleran.cell-wrapper.netconf.service.name" $ | quote }}
  - "--port"
  - {{ ((($values.service).ports).netconf).port | default 8300 | quote }}
  - "--user"
  - "$(username)"
  - "--pass"
  - "$(password)"
  - "--edit"
  - "/rpcs/{{ $job.name }}.xml"
{{- end -}}
