{{- $values := $.Values.netconf -}}
{{- if $values.authentication.create -}}
{{- include
      "accelleran.common.secret"
      (fromYaml (include "accelleran.cell-wrapper.netconf.secret.authentication.args" .))
-}}
{{- end -}}

{{- define "accelleran.cell-wrapper.netconf.secret.authentication.args" -}}
{{- $ := . -}}
{{- $values := $.Values.netconf -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ $values | toYaml | nindent 2 }}

name: {{ include "accelleran.cell-wrapper.netconf.secret.authentication.name" $ }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $values.authentication.username | quote }}
  password: {{ $values.authentication.password | quote }}
{{- end -}}
