apiVersion: v2
appVersion: R4.2.3_karmeliet
dependencies:
- name: acc-common
  repository: https://accelleran.github.io/helm-charts/
  version: 0.1.0
- condition: netconf.enabled
  name: netconf
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 2.4.0
- condition: amf-controller.enabled
  name: amf-controller
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 0.8.1
- condition: cu-up-controller.enabled
  name: cu-up-controller
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 0.6.1
- condition: ds-ctrl.enabled
  name: ds-ctrl
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.2.2
- condition: du-controller.enabled
  name: du-controller
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 0.6.1
- condition: e1-cp.enabled
  name: e1-cp
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.1.1
- condition: f1-ap.enabled
  name: f1-ap
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.1.1
- condition: gnb-controller.enabled
  name: gnb-controller
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 0.6.1
- condition: ng-ap.enabled
  name: ng-ap
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.1.1
- condition: pm-controller.enabled
  name: pm-controller
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 0.6.1
- condition: res-mgr.enabled
  name: res-mgr
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 0.6.1
- condition: rr-ctrl.enabled
  name: rr-ctrl
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.1.1
- condition: sctp-e1.enabled
  name: sctp-e1
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.1.1
- condition: sctp-f1.enabled
  name: sctp-f1
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.1.1
- condition: sctp-ng.enabled
  name: sctp-ng
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 1.1.1
- condition: ho-tester.enabled
  name: ho-tester
  repository: https://accelleran.github.io/5g-helm-charts/
  version: 0.3.1
# The acc-5g-cu-cp chart is deprecated in favor of cu-cp.
deprecated: true
description: DEPRECATED Accelleran 5G CU CP Components
name: acc-5g-cu-cp
type: application
version: 6.0.1
