apiVersion: v1
kind: Service
metadata:
  name: {{ include "xapp_core.fullname" . }}-xapp-headless
  labels:
    {{- include "xapp_core.labels" . | nindent 4 }}
spec:
  clusterIP: None  
  selector:
    {{- include "xapp_core.selectorLabels" . | nindent 4 }}
