apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-storage
  annotations:
    volumeType: local
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass}}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}