apiVersion: v2
name: cu-cp
description: Accelleran 5G CU-CP Components
type: application
version: 10.0.2
# renovate: image=accelleran/cucp-netconf
appVersion: "7.0.5"
dependencies:
  - name: common
    version: 0.4.1
    repository: https://accelleran.github.io/helm-charts/
  - name: nats
    condition: nats.enabled
    version: 1.2.10
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 20.11.1
    repository: https://charts.bitnami.com/bitnami/
