apiVersion: v2
name: cu-cp
description: Accelleran 5G CU-CP Components
type: application
version: 11.0.0
# renovate: image=accelleran/cucp-netconf
appVersion: "7.0.7"
dependencies:
  - name: common
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/
  - name: nats
    condition: nats.enabled
    version: 1.3.2
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 20.11.5
    repository: https://charts.bitnami.com/bitnami/
