apiVersion: v2
name: cu-cp
description: Accelleran 5G CU-CP Components
type: application
version: 7.0.0-rc.0
# renovate: image=accelleran/cucp-netconf
appVersion: "R4.3.5_leffe"
dependencies:
  - name: common
    version: 0.1.2
    repository: https://accelleran.github.io/helm-charts-ng/
  - name: nats
    condition: nats.enabled
    version: 1.1.7
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 18.11.0
    repository: https://charts.bitnami.com/bitnami/
