apiVersion: v2
name: cu-cp
description: Accelleran 5G CU-CP Components
type: application
version: 8.0.2
# renovate: image=accelleran/cucp-netconf
appVersion: "5.0.7"
dependencies:
  - name: common
    version: 0.3.8
    repository: https://accelleran.github.io/helm-charts/
  - name: nats
    condition: nats.enabled
    version: 1.2.4
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 20.1.0
    repository: https://charts.bitnami.com/bitnami/
