global:

  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  persistentLogLevel: info

  nodeSelector: {}

  accelleranLicense:
    enabled: true
    secretName: accelleran-cu-license


bootstrap:
  create: true
  name: ""

  # CU-CP Instance ID
  #   Description:  The Instance ID of the CU-CP component that
  #                 will be used in the bootstrap file.
  #                 The Instance ID must consist of lower case alphanumeric characters
  #                 or '-', start with an alphabetic character, and end with an alphanumeric
  #                 character (e.g. 'my-name',  or 'abc-123', regex used for validation is
  #                 '^[a-z0-9-]+$'). The Instance ID also cannot be longer than 19 characters!
  #
  #   Example:
  # instanceId: "cucp-1"
  #
  instanceId: "cucp-1"

  nats:
    enabled: true
    hostname: ""
    port: 0

drax:
  technology: "5g"
  role: "5g"

nameOverride: ""
fullnameOverride: ""

component: "cu-cp"

natsInitImage:
  repository: accelleran/acc-generic-img
  tag: "0.9.0"
  pullPolicy: IfNotPresent

image:
  repository: accelleran/cu-cp
  tag: ""
  pullPolicy: IfNotPresent

service:
  enabled: true
  name: ""
  type: "LoadBalancer"
  ports:
    e1ap:
      appProtocol: "e1-interface"
      protocol: "SCTP"
      port: 38462
      targetPort: 0
      nodePort: 0
    f1ap:
      appProtocol: "f1-control"
      protocol: "SCTP"
      port: 38472
      targetPort: 0
      nodePort: 0
    netconf:
      appProtocol: "netconf-ssh"
      protocol: "TCP"
      port: 8300
      targetPort: 0
      nodePort: 0
  loadBalancerIP: ""
  externalTrafficPolicy: "Local"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

readinessProbe:
  exec:
    command:
      - "test"
      - "-f"
      - "/tmp/netopeer2-server.pid"
  initialDelaySeconds: 15
  periodSeconds: 30

securityContext:
  fsGroup: 1000

persistence:
  - name: sysrepo
    mountPath: "/workdir/sysrepo"
    storageClassName: ""
    accessModes:
      - "ReadWriteOnce"
    size: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}


nats:
  enabled: false

  natsBox:
    enabled: false

extraResources: []
