{{- if $.Values.notify.enabled -}}
{{-
  include
    "accelleran.common.configMap"
    (fromYaml (include "accelleran.drax.notify.configMap.args" $))
-}}
{{- end -}}


{{- define "accelleran.drax.notify.configMap.args" -}}
{{- $ := . -}}
{{- $values := $.Values.notify -}}

top: {{ $ | toYaml | nindent 2 }}
values: {{ $values | toYaml | nindent 2 }}

name: {{ printf "%s-notify" (include "accelleran.common.fullname" (dict "top" $  "values" $values)) }}

data:
  notify.py: |
    {{ $.Files.Get "configuration/notifications/notify.py" | nindent 4 }}
{{- end -}}
