{{ include 
  "accelleran.common.job" 
  (fromYaml (include "accelleran.influxdb.downsampling.job.args" .)) 
}}

{{- define "accelleran.influxdb.downsampling.job.args" -}}
top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{
    (mergeOverwrite
      (deepCopy (index $.Values "influxdb2" "influxdbDownsampling"))
      (dict "annotations" (dict
        "helm.sh/hook" "post-install,post-upgrade,post-rollback"
        "helm.sh/hook-delete-policy" "before-hook-creation,hook-succeeded"
      ))
    ) | toYaml | nindent 2
  }}

name: "{{ $.Release.Name }}-influxdb2-downsampling-job"
ttlSecondsAfterFinished: 300
backoffLimit: 3
restartPolicy: "OnFailure"
env:
  - name: INFLUXDB_URL
    value: "http://{{ $.Release.Name }}-influxdb2.{{ $.Release.Namespace }}:80"
  - name: ORG
    value: "accelleran"
  - name: INFLUXDB_TOKEN
    valueFrom:
      secretKeyRef:
        name: drax-influxdb2-auth
        key: admin-token
{{- end }}
