apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-drax-auth"
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-drax-auth" $.Release.Name) -}}

{{- with index $existingSecret.data "superadmin-username" }}
  superadmin-username: {{ . }}
{{- else }}
  superadmin-username: {{ $.Values.keycloak.auth.adminUser | b64enc | quote }}
{{- end }}

{{- with index $existingSecret.data "superadmin-email" }}
  superadmin-email: {{ . }}
{{- else }}
  superadmin-email: {{ $.Values.keycloak.auth.adminEmail | b64enc | quote }}
{{- end }}

{{- with index $existingSecret.data "superadmin-password" }}
  superadmin-password: {{ . }}
{{- else }}
  superadmin-password: {{ $.Values.keycloak.auth.adminPassword | default (randAlphaNum 48) | b64enc | quote }}
{{- end }}


{{- with index $existingSecret.data "admin-username" }}
  admin-username: {{ . }}
{{- else }}
  admin-username: {{ $.Values.drax.auth.adminUser | b64enc | quote }}
{{- end }}

{{- with index $existingSecret.data "admin-email" }}
  admin-email: {{ . }}
{{- else }}
  admin-email: {{ $.Values.drax.auth.adminEmail | b64enc | quote }}
{{- end }}

{{- with index $existingSecret.data "admin-password" }}
  admin-password: {{ . }}
{{- else }}
  admin-password: {{ $.Values.drax.auth.adminPassword | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}
