{{- if $.Values.global.alerting.enabled -}}
{{- if eq $.Values.global.alerting.slackToken "" -}}
  {{- fail "Error: global.alerting.slackToken must be defined." -}}
{{- end -}}
{{- end -}}

{{- $secretName := printf "%s-slack-auth" $.Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if $.Values.global.alerting.enabled -}}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if $existingSecret -}}
  {{- $slackToken := get $existingSecret.data "slack-token" | b64dec }}
  {{- if eq $slackToken "" -}}
  {{- fail "Error: Existing slack-token in the secret must not be empty." -}}
  {{- end }}
  slack-token: {{ get ($existingSecret.data) "slack-token" | quote }}
  {{- else }}
  slack-token: {{ $.Values.global.alerting.slackToken | b64enc | quote }}
  {{- end }}
  {{- else }}
  slack-token: ""
  {{- end }}