{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "drax-du-influxdb-auth" -}}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: drax-du-influxdb-auth
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  admin-token: {{ index $.Values "du-metrics-server" "influxdb" "adminUser" "token" | default (randAlphaNum 48) | b64enc | quote}}
  admin-password: {{ index $.Values "du-metrics-server" "influxdb" "adminUser" "password" | default (randAlphaNum 48) | b64enc | quote }}
{{- end }}
