{{- if $.Values.global.alerting.enabled -}}
{{- if eq $.Values.global.alerting.slackToken "" -}}
  {{- fail "A slack token needs to be provided when alerting is enabled (global.alerting.slackToken)." -}}
{{- end -}}
{{- end -}}

{{- $secretName := printf "%s-slack-auth" $.Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

  {{- $existingSlackToken := "" }}
  {{- if and $existingSecret $existingSecret.data (hasKey $existingSecret.data "slack-token") }}
    {{- $existingSlackToken = get ($existingSecret.data) "slack-token" | b64dec }}
  {{- end }}

  {{- $slackToken := $existingSlackToken }}
  {{- if and ((($.Values).global).alerting).enabled (not $slackToken) }}
    {{- $slackToken = $.Values.global.alerting.slackToken }}
  {{- end }}
  slack-token: {{ $slackToken | b64enc | quote }}
