{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "drax-influxdb2-auth" -}}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: drax-influxdb2-auth
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  admin-token: {{ $.Values.influxdb2.adminUser.token | default (randAlphaNum 48) | b64enc | quote}}
  admin-password: {{ $.Values.influxdb2.adminUser.password | default (randAlphaNum 48) | b64enc | quote }}
{{- end }}