apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-drax-auth"
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-drax-auth" $.Release.Name) -}}

{{- with dig "data" "tmp-username" nil $existingSecret }}
  tmp-username: {{ . }}
{{- else }}
  tmp-username: {{ $.Values.keycloak.auth.adminUser | b64enc | quote }}
{{- end }}

{{- with dig "data" "tmp-password" nil $existingSecret }}
  tmp-password: {{ . }}
{{- else }}
  tmp-password: {{ $.Values.keycloak.auth.adminPassword | default (randAlphaNum 64) | b64enc | quote }}
{{- end }}

{{- with dig "data" "superadmin-username" nil $existingSecret }}
  superadmin-username: {{ . }}
{{- else }}
  superadmin-username: {{ $.Values.drax.auth.superadminUser | b64enc | quote }}
{{- end }}

{{- with dig "data" "superadmin-email" nil $existingSecret }}
  superadmin-email: {{ . }}
{{- else }}
  superadmin-email: {{ $.Values.drax.auth.superadminEmail | b64enc | quote }}
{{- end }}

{{- with dig "data" "superadmin-password" nil $existingSecret }}
  superadmin-password: {{ . }}
{{- else }}
  superadmin-password: {{ $.Values.drax.auth.superadminPassword | default (randAlphaNum 48) | b64enc | quote }}
{{- end }}


{{- with dig "data" "admin-username" nil $existingSecret }}
  admin-username: {{ . }}
{{- else }}
  admin-username: {{ $.Values.drax.auth.adminUser | b64enc | quote }}
{{- end }}

{{- with dig "data" "admin-email" nil $existingSecret }}
  admin-email: {{ . }}
{{- else }}
  admin-email: {{ $.Values.drax.auth.adminEmail | b64enc | quote }}
{{- end }}

{{- with dig "data" "admin-password" nil $existingSecret }}
  admin-password: {{ . }}
{{- else }}
  admin-password: {{ $.Values.drax.auth.adminPassword | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}
