apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-drax-auth"
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-drax-auth" $.Release.Name) -}}

{{- with dig "data" "admin-username" nil $existingSecret }}
  admin-username: {{ . }}
{{- else }}
  admin-username: {{ $.Values.drax.auth.adminUser | b64enc | quote }}
{{- end }}

{{- with dig "data" "admin-password" nil $existingSecret }}
  admin-password: {{ . }}
{{- else }}
  admin-password: {{ $.Values.drax.auth.adminPassword | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}