apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-keycloak-postgresql"
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-keycloak-postgresql" $.Release.Name) }}

{{- with dig "data" "postgress-password" nil $existingSecret }}
  postgress-password: {{ . }}
{{- else }}
  postgres-password: {{ $.Values.keycloak.postgresql.auth.postgresPassword | default (randAlphaNum 48) | b64enc | quote }}
{{- end }}

{{- with dig "data" "password" nil $existingSecret }}
  password: {{ . }}
{{- else }}
  password: {{ $.Values.keycloak.postgresql.auth.password | default (randAlphaNum 24) | b64enc | quote }}
{{- end }}
