{{- include
      "accelleran.common.deployment"
      (fromYaml (include "accelleran.service-monitor.deployment.args" $))
-}}

{{- define "accelleran.service-monitor.deployment.args" -}}
{{- $ := . -}}
{{- $fullname := include "accelleran.common.fullname" (dict "top" $) -}}

top:
  {{ $ | toYaml | nindent 2 }}

env:
  - name: MONITORED_NAMESPACES
    value: "{{ tpl $.Values.monitoredNamespaces $ }}"
{{- end -}}
