apiVersion: v2
name: drax
description: Accelleran's dRAX helm chart
type: application
version: 8.0.3
dependencies:
  - name: common
    version: 0.3.4
    repository: https://accelleran.github.io/helm-charts/

  # smo
  - name: dashboard
    condition: dashboard.enabled
    version: 6.0.0
    repository: file://charts/dashboard
  - name: network-state-monitor
    condition: network-state-monitor.enabled
    version: 0.2.0
    repository: file://charts/network-state-monitor
  - name: service-monitor
    condition: service-monitor.enabled
    version: 2.0.0
    repository: file://charts/service-monitor
  - name: service-orchestrator
    condition: service-orchestrator.enabled
    version: 2.0.0
    repository: file://charts/service-orchestrator
  - name: config-api
    condition: config-api.enabled
    version: 3.0.0
    repository: file://charts/config-api
  - name: cell-wrapper
    condition: cell-wrapper.enabled
    version: 4.0.2
    repository: https://accelleran.github.io/helm-charts/
  - name: du-metrics-server
    condition: du-metrics-server.enabled
    version: 0.2.1
    repository: https://accelleran.github.io/helm-charts/
  - name: telemetry-collector
    alias: telemetry-collector
    condition: telemetry-collector.enabled
    version: 1.0.1
    repository: https://accelleran.github.io/helm-charts/

  # ric
  - name: e2-t
    condition: e2-t.enabled
    version: 2.0.0
    repository: file://charts/e2-t

  # xapps
  - name: pm-counters
    condition: pm-counters.enabled
    version: 2.0.0
    repository: file://charts/pm-counters

  # infrastructure
  - name: golang-nkafka
    alias: golang-nkafka-5g
    condition: global.enable5G
    version: 2.0.1
    repository: file://charts/golang-nkafka

  # external

  # monitoring
  - name: grafana
    condition: grafana.enabled
    version: 8.4.3
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    condition: prometheus.enabled
    version: 25.25.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki-stack
    condition: loki-stack.enabled
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
  - name: influxdb
    condition: influxdb.enabled
    version: 4.12.5
    repository: https://helm.influxdata.com/
  - name: vector
    condition: global.enable5G
    version: 0.35.0
    repository: https://helm.vector.dev
  - name: kminion
    condition: kminion.enabled
    version: 0.14.0
    repository: https://charts.redpanda.com
  - name: influxdb2
    condition: influxdb2.enabled
    version: 2.1.2
    repository: https://helm.influxdata.com/

  # infrastructure
  - name: kafka
    condition: kafka.enabled
    version: 30.0.3
    repository: https://charts.bitnami.com/bitnami/
  - name: nats
    condition: nats.enabled
    version: 1.2.2
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 20.0.0
    repository: https://charts.bitnami.com/bitnami/
