apiVersion: v2
name: drax
description: Accelleran's dRAX helm chart
type: application
version: 13.1.2
dependencies:
  - name: common
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/

  # smo
  - name: dashboard
    condition: dashboard.enabled
    version: 6.0.0
    repository: file://charts/dashboard
  - name: network-state-monitor
    condition: network-state-monitor.enabled
    version: 0.2.0
    repository: file://charts/network-state-monitor
  - name: service-monitor
    condition: service-monitor.enabled
    version: 2.0.0
    repository: file://charts/service-monitor
  - name: service-orchestrator
    condition: service-orchestrator.enabled
    version: 2.0.0
    repository: file://charts/service-orchestrator
  - name: config-api
    condition: config-api.enabled
    version: 3.0.0
    repository: file://charts/config-api
  - name: cell-wrapper
    condition: cell-wrapper.enabled
    version: 6.2.3
    repository: https://accelleran.github.io/helm-charts/
  - name: du-metrics-server
    condition: du-metrics-server.enabled
    version: 0.4.13
    repository: https://accelleran.github.io/helm-charts/
  - name: telemetry-collector
    condition: telemetry-collector.enabled
    version: 2.0.2
    repository: https://accelleran.github.io/helm-charts/

  # ric
  - name: e2-t
    condition: e2-t.enabled
    version: 2.0.0
    repository: file://charts/e2-t

  # xapps
  - name: pm-counters
    condition: pm-counters.enabled
    version: 2.0.0
    repository: file://charts/pm-counters

  # infrastructure
  - name: golang-nkafka
    alias: golang-nkafka-5g
    condition: global.enable5G
    version: 2.0.1
    repository: file://charts/golang-nkafka

  # external

  # authentication
  - name: ingress-nginx
    condition: ingress-nginx.enabled
    tags:
      - authentication
    version: 4.12.1
    repository: https://kubernetes.github.io/ingress-nginx
  - name: oauth2-proxy
    condition: oauth2-proxy.enabled
    tags:
      - authentication
    version: 7.12.11
    repository: https://oauth2-proxy.github.io/manifests
  - name: keycloak
    condition: keycloak.enabled
    tags:
      - authentication
    version: 24.6.2
    repository: https://charts.bitnami.com/bitnami/

  # monitoring
  - name: grafana
    condition: grafana.enabled
    version: 8.13.1
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    condition: prometheus.enabled
    version: 27.11.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki-gateway
    condition: loki-gateway.enabled
    tags:
      - logs
      - events
    version: 0.1.11
    repository: https://accelleran.github.io/helm-charts/
  - name: grafana-loki
    alias: loki
    condition: loki.enabled
    tags:
      - logs
      - events
    version: 4.8.4
    repository: https://charts.bitnami.com/bitnami/
  - name: loki-deleter
    condition: loki-deleter.enabled
    tags:
      - logs
    version: 0.1.8
    repository: https://accelleran.github.io/helm-charts/
  - name: minio
    condition: minio.enabled
    tags:
      - logs
      - events
    version: 5.4.0
    repository: https://charts.min.io/
  - name: promtail
    alias: promtail-logs
    condition: promtail-logs.enabled
    tags:
      - logs
    version: 6.16.6
    repository: https://grafana.github.io/helm-charts/
  - name: promtail
    alias: promtail-events
    condition: promtail-events.enabled
    tags:
      - events
    version: 6.16.6
    repository: https://grafana.github.io/helm-charts/
  - name: influxdb2
    condition: influxdb2.enabled
    version: 2.1.2
    repository: https://helm.influxdata.com/
  - name: kminion
    condition: kminion.enabled
    version: 0.14.1
    repository: https://charts.redpanda.com

  # infrastructure
  - name: kafka
    condition: kafka.enabled
    version: 31.5.0
    repository: https://charts.bitnami.com/bitnami/
  - name: nats
    condition: nats.enabled
    version: 1.3.4
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 20.13.3
    repository: https://charts.bitnami.com/bitnami/
