global:
  nodeSelector:
    drax.accelleran.com/schedule: "true"

du-metrics-server:
  influxdb:
    nodeSelector:
      drax.accelleran.com/schedule: "true"

kafka:
  controller:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  broker:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  metrics:
    kafka:
      nodeSelector:
        drax.accelleran.com/schedule: "true"
  provisioning:
    nodeSelector:
      drax.accelleran.com/schedule: "true"

nats:
  podTemplate:
    merge:
      spec:
        nodeSelector:
          drax.accelleran.com/schedule: "true"

redis:
  master:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  replica:
    nodeSelector:
      drax.accelleran.com/schedule: "true"

prometheus:
  nodeSelector:
    drax.accelleran.com/schedule: "true"
  prometheus-pushgateway:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  kube-state-metrics:
    nodeSelector:
      drax.accelleran.com/schedule: "true"

grafana:
  nodeSelector:
    drax.accelleran.com/schedule: "true"

loki:
  compactor:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  gateway:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  indexGateway:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  distributor:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  ingester:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  querier:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  queryFrontend:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  queryScheduler:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  ruler:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  tableManager:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  memcachedchunks:
    nodeSelector:
      drax.accelleran.com/schedule: "true"
  memcachedfrontend:
    nodeSelector:
      drax.accelleran.com/schedule: "true"

minio:
  nodeSelector:
    drax.accelleran.com/schedule: "true"
  postJob:
    nodeSelector:
      drax.accelleran.com/schedule: "true"

promtail-logs: {}

promtail-notifications:
  nodeSelector:
    drax.accelleran.com/schedule: "true"

influxdb2:
  nodeSelector:
    drax.accelleran.com/schedule: "true"
    
kminion:
  nodeSelector:
    drax.accelleran.com/schedule: "true"
