apiVersion: v2
name: cell-wrapper
description: Accelleran's cell-wrapper helm chart
type: application
version: 3.0.0
# renovate: image=accelleran/cw-netconf
appVersion: "CW3.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: https://accelleran.github.io/helm-charts-ng/
  - name: nats
    condition: nats.enabled
    version: 1.1.7
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 18.8.2
    repository: https://charts.bitnami.com/bitnami/
