apiVersion: v2
name: cell-wrapper
description: Accelleran's cell-wrapper helm chart
type: application
version: 7.2.0
# renovate: image=accelleran/cw-netconf versioning=semver
appVersion: "7.2.0"
dependencies:
  - name: common
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/
  - name: nats
    condition: nats.enabled
    version: 1.3.7
    repository: https://nats-io.github.io/k8s/helm/charts/
