apiVersion: v2
name: cell-wrapper
description: Accelleran's cell-wrapper helm chart
type: application
version: 7.0.0
# renovate: image=accelleran/cw-netconf versioning=semver
appVersion: "6.2.1"
dependencies:
  - name: common
    version: 0.4.1
    repository: https://accelleran.github.io/helm-charts/
  - name: nats
    condition: nats.enabled
    version: 1.2.11
    repository: https://nats-io.github.io/k8s/helm/charts/
