apiVersion: v2
name: cell-wrapper
description: Accelleran's cell-wrapper helm chart
type: application
version: 2.3.0
# renovate: image=accelleran/cw-netconf
appVersion: "CW2.3.0"
dependencies:
  - name: common
    version: 0.2.0
    repository: https://accelleran.github.io/helm-charts-ng/
  - name: nats
    condition: nats.enabled
    version: 1.1.6
    repository: https://nats-io.github.io/k8s/helm/charts/
