apiVersion: v2
name: cell-wrapper
description: Accelleran's cell-wrapper helm chart
type: application
version: 4.0.0
# renovate: image=accelleran/cw-netconf versioning=semver
appVersion: "4.0.0"
dependencies:
  - name: common
    version: 0.3.0
    repository: https://accelleran.github.io/helm-charts/
  - name: nats
    condition: nats.enabled
    version: 1.1.12
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: redis
    condition: redis.enabled
    version: 19.5.0
    repository: https://charts.bitnami.com/bitnami/
