global:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

  bootstrap:
    create: true
    configMapName: ""

    # CW Instance ID
    #   Description:  The Instance ID of the CW component that
    #                 will be used in the bootstrap file.
    #                 The Instance ID must consist of lower case alphanumeric characters
    #                 or '-', start with an alphabetic character, and end with an alphanumeric
    #                 character (e.g. 'my-name',  or 'abc-123', regex used for validation is
    #                 '^[a-z0-9-]+$'). The Instance ID also cannot be longer than 19 characters!
    #
    #   Example:
    # instanceId: "cw"
    #
    instanceId: "cw"

    redis:
      hostname: "ric-redis-5g"
      port: "6379"

    nats:
      hostname: "ric-nats-5g"
      port: "4222"

  drax:
    technology: "5g"
    role: "5g"

  # dRAX Specific Node Selector
  #   Description: This is a special nodeSelector field implemented for the
  #                Accelleran 5G Helm charts. You need to first label your
  #                node in Kubernetes with a label "draxName" and give it a
  #                <value>. For example for node <node_name>, you can use the
  #                following command to label it:
  #                kubectl label node <node_name> draxName=<value>.
  #                Then in "draxName" set the value of the label you chose for
  #                the node. This will in effect install all the 5G Application
  #                on that node, without the need to edit all individual helm
  #                charts. In case you want to add other nodeSelector options,
  #                you have to add them to the helm chart specific values files.
  #   Value type: bool
  #   Example:
  #
  draxNodeSelectorEnabled: false
  draxNodeSelector:
    draxName: "main"

  # Cell Wrapper config
  # Documentation: https://accelleran.atlassian.net/wiki/spaces/GS/pages/2298183683/Configuration
  config:

    # Enables/disables cell wrapper config
    #   Description:  Sets whether the configuration of the cell wrapper is
    #                 done by the helm charts.
    #                 If enabled, all old configuration underneath the configured instanceId
    #                 will be deleted.
    #   Value type:   boolean
    #   Example:
    # enabled: true
    enabled: false

    # (Un)lock cell wrapper's admin state
    #   Description:  Locks or unlocks the admin state of the cell wrapper.
    #   Value type:   boolean
    #   Example:
    # unlockAdminState: false
    unlockAdminState: true

    # Global cell wrapper config
    global:

      # Global "install" cell wrapper config
      #   Description:  Sets the global "install" configuration of the cell wrapper.
      #                 This should be xml that would be contained within the root
      #                 "cw-install" container.
      #   Value type:   string
      #   Example:
      # install: |-
      #   <!-- Global CW install config -->
      install: null
      
      # Global "internal" cell wrapper config
      #   Description:  Sets the global "internal" configuration of the cell wrapper.
      #                 This should be xml that would be contained within the root
      #                 "cw-internal" container.
      #   Value type:   string
      #   Example:
      # internal: |-
      #   <!-- Global CW internal config -->
      internal: null

      # Global "RAN" cell wrapper config
      #   Description:  Sets the global "RAN" configuration of the cell wrapper.
      #                 This should be xml that would be contained within the root
      #                 "cw-ran" container.
      #   Value type:   string
      #   Example:
      # install: |-
      #   <!-- Global CW RAN config -->
      ran: null

    # DU configurations
    #   Description:  Sets the DUs the cell wrapper should control.
    dus: []

    # # DU name (mandatory)
    # #   Description:  Sets the DU's name which is used as a key internally.
    # #                 Only use alpha-numeric characters and a dash.
    # #                 Maximum supported length is 150 characters.
    # #   Value type:   string
    # #   Example:
    # # name: "du-1"
    # - name: "du-1"

    #   # DU "install" config
    #   #   Description:  Sets the DU's "install" configuration.
    #   #                 This should be xml that would be contained within the
    #   #                 "du" container.
    #   #   Value type:   string
    #   #   Example:
    #   # install: |-
    #   #   <type>effnet</type>
    #   #   <ssh-connection-details xc:operation="create">
    #   #     <host>127.0.0.1</host>
    #   #     <port>22</port>
    #   #     <username>root</username>
    #   #   </ssh-connection-details>
    #   install: null

    #   # DU "internal" config
    #   #   Description:  Sets the DU's "internal" configuration.
    #   #                 This should be xml that would be contained within the
    #   #                 "du" container.
    #   #   Value type:   string
    #   #   Example:
    #   # internal: |-
    #   #   <auto-repair xc:operation="create">
    #   #     <enable>true</enable>
    #   #   </auto-repair>
    #   internal: null

    #   # DU "RAN" config
    #   #   Description:  Sets the DU's "RAN" configuration.
    #   #                 This should be xml that would be contained within the
    #   #                 "du" container.
    #   #   Value type:   string
    #   #   Example:
    #   # ran: |-
    #   #   <gnb-id>1</gnb-id>
    #   #   <gnb-id-length>22</gnb-id-length>
    #   #   <gnb-du-id>1</gnb-du-id> 
    #   #   <cu>127.0.0.1</cu>
    #   #   <admin-state>unlocked</admin-state>
    #   ran: null

    #   # RU configurations
    #   #   Description:  Sets the RUs the cell wrapper should control and
    #   #                 link to the current DU.
    #   rus:
      
    #     # RU name (mandatory)
    #     #   Description:  Sets the RU's name which is used as a key internally.
    #     #                 Only use alpha-numeric characters and a dash.
    #     #                 Maximum supported length is 150 characters.
    #     #   Value type:   string
    #     #   Example:
    #     # name: "ru-1"
    #   - name: "ru-1"

    #     # RU "install" config
    #     #   Description:  Sets the RU's "install" configuration.
    #     #                 This should be xml that would be contained within the
    #     #                 "ru" container.
    #     #   Value type:   string
    #     #   Example:
    #     # install: |-
    #     #   <type>benetel650</type>
    #     #   <ssh-connection-details xc:operation="create">
    #     #     <host>127.0.0.1</host>
    #     #     <port>22</port>
    #     #     <username>root</username>
    #     #   </ssh-connection-details>
    #     install: null

    #     # RU "internal" config
    #     #   Description:  Sets the RU's "internal" configuration.
    #     #                 This should be xml that would be contained within the
    #     #                 "ru" container.
    #     #   Value type:   string
    #     #   Example:
    #     # internal: |-
    #     #   <health-check xc:operation="create">
    #     #     <host-reachability xc:operation="create">
    #     #         <timeout>5</timeout>
    #     #     </host-reachability>
    #     #   </health-check>
    #     internal: null

nameOverride: ""
fullnameOverride: ""

cw-ctrl:
  enabled: true
  
  nameOverride: "cw-ctrl"
  fullnameOverride: ""

  containerName: "cw-ctrl"

  initImage:
    repository: accelleran/acc-generic-img
    pullPolicy: IfNotPresent
    tag: "latest"

  image:
    repository: accelleran/cw-ctrl
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  extraEnvs: []

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  draxNodeSelectorEnabled: false
  draxNodeSelector:
    draxName: "{{ $.Values.global.draxNodeSelector.draxName }}"

  nodeSelector: {}

  tolerations: []

  affinity: {}


cw-inst:
  enabled: true

  nameOverride: "cw-inst"
  fullnameOverride: ""

  containerName: "cw-inst"

  secrets:
    sshKey: "cw-ssh-key"

  baseConfig:
    configDir: "/home/accelleran/5G/config"
    vendors: null
      # effnet:
      # - file: "default.du.json"
      #   data: |
      #     <data>
      # - file: "default.kpi.json"
      #   data: |
      #     <data>
      # phluido:
      # - file: "default.l1.cfg"
      #   data: |
      #     <data>
      # nodeh:
      # - file: "default.json"
      #   data: |
      #     <data>

  replicaCount: null
  spareInstanceCount: 0

  image:
    repository: "accelleran/cw-inst"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: null
    maxReplicas: null
    spareReplicas: null
    factorReplicas: null

  draxNodeSelectorEnabled: false
  draxNodeSelector:
    draxName: "{{ $.Values.global.draxNodeSelector.draxName }}"

  nodeSelector: {}

  tolerations: []

  affinity: {}


instance-scaler:
  enabled: true

  nameOverride: "instance-scaler"
  fullnameOverride: ""

  containerName: "instance-scaler"

  image:
    repository: accelleran/instance-scaler
    pullPolicy: IfNotPresent
    tag: "v0.1.0"

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  rbac:
    enabled: true
    rules:
      - apiGroups:
        - apps
        resources:
        - deployments
        verbs:
        - "get"
        - "update"


netconf:
  enabled: true

  nameOverride: "netconf"
  fullnameOverride: ""

  containerName: "netconf"

  image:
    repository: accelleran/cw-netconf
    pullPolicy: IfNotPresent
    tag: ""

  readinessProbe:
    exec:
      command:
        - "test"
        - "-f"
        - "/ready"
    initialDelaySeconds: 15
    periodSeconds: 30

  service:
    enabled: true
    name: ""
    type: "NodePort"
    portName: "netconf"
    protocol: "TCP"
    port: 8300
    targetPort: null
    nodePort: null

  initNetconfDefaultPath:
    componentType: cw

  initEditConfig:
    enabled: "{{ .Values.global.config.enabled }}"
    config:
      - |-
        <cw-install xmlns="http://accelleran.com/ns/yang/accelleran-cw-install" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="delete"/>
      - |-
        <cw-internal xmlns="http://accelleran.com/ns/yang/accelleran-cw-internal" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="delete"/>
      - |-
        <cw-ran xmlns="http://accelleran.com/ns/yang/accelleran-cw-ran" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="delete"/>
      - |-
        <cw-install xmlns="http://accelleran.com/ns/yang/accelleran-cw-install" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
          {{- range $index, $du := .Values.global.config.dus }}
          <du xc:operation="create">
            <name>{{ $du.name }}</name>
            {{- with $du.install }}
            {{- . | nindent 4 }}
            {{- end }}
          </du>
          {{ range $index, $ru := $du.rus }}
          <ru xc:operation="create">
            <name>{{ $ru.name }}</name>
            {{- with $ru.install }}
            {{- . | nindent 4 }}
            {{- end }}
            <du>{{ $du.name }}</du>
          </ru>
          {{- end }}
          {{- end }}
          {{- with .Values.global.config.global.install }}
          {{ . | nindent 2 }}
          {{- end }}
        </cw-install>
      - |-
        <cw-internal xmlns="http://accelleran.com/ns/yang/accelleran-cw-internal" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
          {{- range $index, $du := .Values.global.config.dus }}
          <du xc:operation="create">
            <name>{{ $du.name }}</name>
            {{- with $du.internal }}
            {{- . | nindent 4 }}
            {{- end }}
          </du>
          {{ range $index, $ru := $du.rus }}
          <ru xc:operation="create">
            <name>{{ $ru.name }}</name>
            {{- with $ru.internal }}
            {{- . | nindent 4 }}
            {{- end }}
          </ru>
          {{- end }}
          {{- end }}
          {{- with .Values.global.config.global.internal }}
          {{ . | nindent 2}}
          {{- end }}
        </cw-internal>
      - |-
        <cw-ran xmlns="http://accelleran.com/ns/yang/accelleran-cw-ran" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
          {{- range $index, $du := .Values.global.config.dus }}
          <du xc:operation="create">
            <name>{{ $du.name }}</name>
            {{- with $du.ran }}
            {{- . | nindent 4 }}
            {{- end }}
          </du>
          {{- end }}
          {{- with .Values.global.config.global.ran }}
          {{ . | nindent 2 }}
          {{- end }}
        </cw-ran>
      - |-
        <cw-internal xmlns="http://accelleran.com/ns/yang/accelleran-cw-internal" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
          <admin-state>
          {{- if .Values.global.config.unlockAdminState -}}
          unlocked
          {{- else -}}
          locked
          {{- end -}}
          </admin-state>
        </cw-internal>

jobs: []
  # - name: "<job_name>"
  #   schedule: "<cron_schedule>"
  #   netconfHost: "<netconf_host>" # optional
  #   netconfPort: "<netconf_port>" # optional
  #   rpc: |-
  #     <!-- full edit-config rpc -->
