apiVersion: v2
name: service-orchestrator
description: The dRAX Service Orchestrator
type: application
version: 2.0.0
# renovate: image=accelleran/service-orchestrator
appVersion: 1.1.0
dependencies:
  - name: common
    version: 0.3.0
    repository: https://accelleran.github.io/helm-charts/
