global: {}

kubeIp: "10.55.1.2"
default5gVersion: "9"
# renovate: repository=https://accelleran.github.io/helm-charts chart=xapp-hello-world
defaultDevEnvVersion: "4"

config:
  namespaces:
    - "default"
  uploadFolder: "uploads"
  serviceMonitorUrl: ""
  uploadFolderSubDirectories:
    - "cu-cp"
    - "cu-up"
    - "xapp"
  prefix5g: "acc"
  prefix5gOld: "acc-5g"
  cucpRepoName: "acc-5g-cu-cp"
  cuupRepoName: "acc-5g-cu-up"
  cuRepoUrl: "https://accelleran.github.io/helm-charts/"

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: accelleran/service-orchestrator
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: accelleran-secret

accelleranLicense:
  enabled: true
  secretName: "accelleran-license"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: true
  name: ""
  type: ClusterIP
  ports:
    http:
      port: 80
      targetPort: 8080
      nodePort: null
      protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    -
      # host: example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: http
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  enabled: true
  rules:
    - apiGroups:
        - "*"
      resources:
        - "*"
      verbs:
        - "*"

extraResources: []
