apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cnpg-timescaledb-user-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.auth.username }}
  password: {{ include "cnpg.userPassword" . | quote }}
