{{- include
      "accelleran.common.service"
      (dict
        "top" $
        "values" (index $.Values "netconf")
        "serviceName" (include "accelleran.cell-wrapper.netconf.service.name" .)
      )
-}}
