{{- include
      "accelleran.common.statefulset"
      (fromYaml (include "accelleran.cell-wrapper.netconf.statefulset.args" .))
-}}


{{- define "accelleran.cell-wrapper.netconf.statefulset.args" -}}
{{- $ := . -}}
{{- $values := (index $.Values "netconf") -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ $values | toYaml | nindent 2 }}

initContainers:
- {{ fromYaml (include "accelleran.common.init.nats" (fromYaml (include "accelleran.cell-wrapper.netconf.init.args" .))) | toYaml | nindent 2 }}

env:
  - name: __APPNAME
    value: cellWrapperNetconf
{{- with (include "accelleran.common.bootstrap.instanceId" (dict "top" $)) }}
  - name: INSTANCE_FILTER
    value: {{ . | quote }}
{{- end }}
envFrom:
  - configMapRef:
      name: {{ include "accelleran.common.bootstrap.configMapName" (dict "top" $) | quote }}
{{- end -}}


{{- define "accelleran.cell-wrapper.netconf.init.args" -}}
{{- $ := . -}}
{{- $values := (index $.Values "netconf") -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ omit $values "readinessProbe" | toYaml | nindent 2 }}

bootstrapConfigMapName: {{ include "accelleran.common.bootstrap.configMapName" (dict "top" $) | quote }}
{{- end -}}
