apiVersion: v2
name: du-metrics-server
description: Accelleran's DU metrics server
type: application
version: 0.5.0
# renovate: image=accelleran/du-metrics-server versioning=semver
appVersion: 4.0.1
dependencies:
  - name: common
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/
  - name: influxdb2
    alias: influxdb
    condition: influxdb.enabled
    version: 2.1.2
    repository: https://helm.influxdata.com/
