du-metrics-server:
  config:
    testbed: default

  replicaCount: 1

  initImage:
    influxdb:
      repository: accelleran/acc-generic-img
      pullPolicy: IfNotPresent
      tag: "0.8.0"

  image:
    repository: accelleran/du-metrics-server
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  accelleranLicense:
    enabled: false

  extraEnvs: []

  extraLabels: {}
  annotations: {}

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  service:
    enabled: true
    name: ""
    type: NodePort
    ports:
      metric:
        port: 55555
        targetPort: 55555
        nodePort: 31555
        protocol: UDP


influxdb:
  enabled: true

  adminUser:
    organization: "accelleran"
    bucket: "default"
    retention_policy: "0s"
    user: "admin"
    password: ""
    token: ""
    # existingSecret: influxdb-auth

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    mountPath: /var/lib/influxdb2
    subPath: ""

  service:
    annotations: {}
    labels: {}
    type: ClusterIP
    portName: http
    port: 80
    targetPort: 8086
