apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-timescaledb-provisioning
data:
  timescaledb.sql: |
    {{- $root := . }}
    {{- $files := $root.Files.Glob "configuration/timescaledb/tables/*.sql" }}
    {{- range $path, $fileBytes := $files }}
    -- START: {{ $path }}
{{ tpl (printf "%s" $fileBytes) $root | indent 4 }}
    -- END: {{ $path }}
    {{- end }}
