apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-atlas-db-url
type: Opaque
stringData:
  url: postgres://{{ .Values.cnpg.auth.username }}:{{ include "cnpg.userPassword" . }}@{{ .Release.Name }}-cnpg-timescaledb-rw.default.svc.cluster.local:5432/devdb
