{{ range until (atoi (include "accelleran.cu-up.upsCount" $)) }}
---
{{ include
      "accelleran.common.service"
      (fromYaml (include "accelleran.cu-up.upsService" (dict "top" $ "ordinal" .)))
}}
{{ end }}


{{- define "accelleran.cu-up.upsService" -}}
{{- $ := get . "top" -}}
{{- $values := index $.Values "ups" -}}
{{- $ordinal := get . "ordinal" -}}

top:
  {{ $ | toYaml | nindent 2 }}

values:
  {{ (index $.Values "ups") | toYaml | nindent 2}}

serviceName: {{ (include "accelleran.cu-up.gtp-u.service.name" (list $ $ordinal)) | quote }}

selectorLabels:
  {{ include "accelleran.common.selectorLabels" (dict "top" $ "values" $values) | nindent 2 }}
  up-stack-id: {{ $ordinal | quote }}
{{- end -}}
