{{- $values := index $.Values "netconf" -}}
{{- $mergedValues := mergeOverwrite
                      (deepCopy $values)
                      (dict "nameOverride" (index $.Values "cu-up" "nameOverride"))
-}}

{{- include
      "accelleran.common.service"
      (dict
        "top" $
        "values" $mergedValues
        "name" (include "accelleran.cu-up.netconf.service.name" .)
        "selectorLabels" (merge
          (include "accelleran.common.selectorLabels" (dict "top" $ "values" $mergedValues) | fromYaml)
          (dict "app.kubernetes.io/component" $values.component)
        )
        "labels" (include "accelleran.common.labels" (dict "top" $ "values" $mergedValues) | fromYaml)
      )
-}}
