{{ range until (atoi (include "accelleran.cu-up.upsCount" $)) }}
---
{{ include
      "accelleran.common.service"
      (fromYaml (include "accelleran.cu-up.upsService" (dict "top" $ "ordinal" .)))
}}
{{ end }}


{{- define "accelleran.cu-up.upsService" -}}
{{- $ := get . "top" -}}
{{- $values := index $.Values "ups" -}}
{{- $ordinal := get . "ordinal" -}}

top:
  {{ $ | toYaml | nindent 2 }}

values:
  {{
    (mergeOverwrite
      (deepCopy (index $.Values "cu-up"))
      (dict "service" (index $.Values "ups" "service"))
    )
    | toYaml | nindent 2
  }}

serviceName: {{ (include "accelleran.cu-up.gtp-u.service.name" (list $ $ordinal)) | quote }}

selectorLabels:
  app.kubernetes.io/name: "ups"
  app.kubernetes.io/instance: {{ include "accelleran.common.instance" (dict "top" $ "values" $values) | quote }}
  up-stack-id: {{ $ordinal | quote }}
{{- end -}}
