global:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  accelleranLicense:
    enabled: true
    imageSuffix: "-license"

  persistentLogLevel: info

  nodeSelector: {}

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: accelleran/telemetry-collector
  pullPolicy: IfNotPresent
  tag: ""

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: true
  name: ""
  type: ClusterIP
  ports:
    udp:
      port: 55555
      targetPort: 55555
      protocol: UDP

influxdbAuthSecret: "{{ $.Release.Name }}-influxdb2-auth"
timescaledbAuthSecret: "{{ $.Release.Name }}-cnpg-timescaledb-user-secret"

config:
  internal:
    kafka:
      url: ""
    influxDB:
      url: ""
      token: ""
      org: ""
    timescaleDB:
      url: ""
      user: ""
      password: ""
      dbName: ""
      sslMode: "require"
      connectTimeout: 5
      statementTimeout: 30000
      maxOpenConns: 5
      maxIdleConns: 5
      connMaxLifetime: 300

  pipelines:
    - name: "cu_measurements"
      component: "cu"
      vendor: "accelleran"
      enabled: "true"
      consumers:
        natsConsumer:
          url: ""
          subjects: "*.5G_MEAS_INFO.*.*.*.*"
      publishers:
        # kafkaPublisher:
        #   topic: "accelleran.drax.5g.ric.o1.ves"
        influxPublisher:
          defaultBucket: "meas5g"
          buckets:
            RrcMeasurementReport: "rrc_measurements"
    - name: "pm_counters"
      component: "cu"
      vendor: "accelleran"
      enabled: "true"
      consumers:
        natsConsumer:
          url: ""
          subjects: "*.CUCP_COUNTERS_INFO,*.CUUP_COUNTERS_INFO"
      publishers:
        # kafkaPublisher:
        #   topic: "accelleran.drax.5g.ric.o1.ves"
        influxPublisher:
          defaultBucket: "default_performance_metrics"
          buckets:
            RRCConnEstabAtt: "rrc_connection_metrics"
            RRCConnEstabSucc: "rrc_connection_metrics"
            RRCConnReestabAtt: "rrc_connection_metrics"
            RRCConnReestabSucc: "rrc_connection_metrics"
            MMHoExeIntraReq: "handover_and_mobility_metrics"
            MMHoExeIntraSucc: "handover_and_mobility_metrics"
            RRCConnMean: "rrc_connection_metrics"
            RRCConnMax: "rrc_connection_metrics"
            SMPDUSessionSetupReq: "pdu_session_management_metrics"
            SMPDUSessionSetupReqSnssai: "pdu_session_management_metrics"
            SMPDUSessionSetupFail: "pdu_session_management_metrics"
            L1MSSRSRP: "rrc_measurements"
            MMHoPrepInterReq: "handover_and_mobility_metrics"
            MMHoPrepInterSucc: "handover_and_mobility_metrics"
            MMHoPrepInterFail: "handover_and_mobility_metrics"
            MMHoResAlloInterReq: "handover_and_mobility_metrics"
            MMHoResAlloInterSucc: "handover_and_mobility_metrics"
            MMHoResAlloInterFail: "handover_and_mobility_metrics"
            MMHoExeInterReq: "handover_and_mobility_metrics"
            AccDRBEstabAtt5QiSnssai: "radio_resource_utilization_metrics"
            DRBEstabSuccSnssai: "radio_resource_utilization_metrics"
            DRBEstabSucc5Qi: "radio_resource_utilization_metrics"
            DRBRelActNbr5QiSnssai: "radio_resource_utilization_metrics"
            DRBRelActNbrSnssai: "radio_resource_utilization_metrics"
            DRBRelActNbr5Qi: "radio_resource_utilization_metrics"
            MMHoExeInterReqTimeMean: "handover_and_mobility_metrics"
            MMHoExeInterReqTimeMax: "handover_and_mobility_metrics"
            AccGTPThpDl: "throughput_metrics"
            AccGTPThpDlQfiSnssaiPlmn: "throughput_metrics"
            AccGTPThpUl: "throughput_metrics"
            AccGTPThpUlQfiSnssaiPlmn: "throughput_metrics"
            AccDRBPdcpSduDelayDlQfiSnssaiPlmn: "radio_resource_utilization_metrics"
            AccDRBF1UPacketLossRateUlQoS: "radio_resource_utilization_metrics"
            AccDRBF1UPacketLossRateUlQfiSnssaiPlmn: "radio_resource_utilization_metrics"
            AccDRBF1UPacketLossRateUlSnssai: "radio_resource_utilization_metrics"
            AccDRBPdcpPacketDropRateDlQoS: "radio_resource_utilization_metrics"
            AccDRBPdcpPacketDropRateDlSnssai: "radio_resource_utilization_metrics"
            AccDRBPdcpPacketDropRateDlQfiSnssaiPlmn: "radio_resource_utilization_metrics"
            DRBPdcpSduDelayDlQoS: "radio_resource_utilization_metrics"
            DRBPdcpSduDelayDlSnssai: "radio_resource_utilization_metrics"
            DRBPdcpSduDelayDlDistQos: "radio_resource_utilization_metrics"
            DRBPdcpSduDelayDlDist: "radio_resource_utilization_metrics"
            DRBPdcpSduDelayDlDistSnssai: "radio_resource_utilization_metrics"
            AccDRBPdcpSduDelayDlDistQfiSnssaiPlmn: "radio_resource_utilization_metrics"
            AccDRBEstabSucc5QiSnssai: "radio_resource_utilization_metrics"
            DRBEstabAttSnssai: "radio_resource_utilization_metrics"
            DRBEstabAtt5Qi: "radio_resource_utilization_metrics"
        timescalePublisher:
          tables:
            RRCConnEstabAtt: "rrc_conn_estab_att"
            RRCConnEstabSucc: "rrc_conn_estab_succ"
            RRCConnReestabAtt: "rrc_conn_reestab_att"
            RRCConnReestabSucc: "rrc_conn_reestab_succ"
            MMHoExeIntraReq: "mm_ho_exe_intra_req"
            MMHoExeIntraSucc: "mm_ho_exe_intra_succ"
            RRCConnMean: "rrc_conn_mean"
            RRCConnMax: "rrc_conn_max"
            SMPDUSessionSetupReq: "smp_du_session_setup_req"
            SMPDUSessionSetupReqSnssai: "smp_du_session_setup_req_snssai"
            SMPDUSessionSetupFail: "smp_du_session_setup_fail"
            MMHoPrepInterReq: "mm_ho_prep_inter_req"
            MMHoPrepInterSucc: "mm_ho_prep_inter_succ"
            MMHoPrepInterFail: "mm_ho_prep_inter_fail"
            MMHoResAlloInterReq: "mm_ho_res_allo_inter_req"
            MMHoResAlloInterSucc: "mm_ho_res_allo_inter_succ"
            MMHoResAlloInterFail: "mm_ho_res_allo_inter_fail"
            MMHoExeInterReq: "mm_ho_exe_inter_req"
            AccDRBEstabAtt5QiSnssai: "acc_drb_estab_att_5qi_snssai"
            DRBEstabSuccSnssai: "drb_estab_succ_snssai"
            DRBEstabSucc5Qi: "drb_estab_succ_5qi"
            DRBRelActNbr5QiSnssai: "drb_rel_act_nbr_5qi_snssai"
            DRBRelActNbrSnssai: "drb_rel_act_nbr_snssai"
            DRBRelActNbr5Qi: "drb_rel_act_nbr_5qi"
            MMHoExeInterReqTimeMean: "mm_ho_exe_inter_req_time_mean"
            MMHoExeInterReqTimeMax: "mm_ho_exe_inter_req_time_max"
            AccGTPThpDl: "acc_gtp_thp_dl"
            AccGTPThpDlQfiSnssaiPlmn: "acc_gtp_thp_dl_qfi_snssai_plmn"
            AccGTPThpUl: "acc_gtp_thp_ul"
            AccGTPThpUlQfiSnssaiPlmn: "acc_gtp_thp_ul_qfi_snssai_plmn"
            AccDRBPdcpSduDelayDlQfiSnssaiPlmn: "acc_drb_pdcp_sdu_delay_dl_qfi_snssai_plmn"
            AccDRBF1UPacketLossRateUlQoS: "acc_drb_f1u_packet_loss_rate_ul_qos"
            AccDRBF1UPacketLossRateUlQfiSnssaiPlmn: "acc_drb_f1u_packet_loss_rate_ul_qfi_snssai_plmn"
            AccDRBF1UPacketLossRateUlSnssai: "acc_drb_f1u_packet_loss_rate_ul_snssai"
            AccDRBPdcpPacketDropRateDlQoS: "acc_drb_pdcp_packet_drop_rate_dl_qos"
            AccDRBPdcpPacketDropRateDlSnssai: "acc_drb_pdcp_packet_drop_rate_dl_snssai"
            AccDRBPdcpPacketDropRateDlQfiSnssaiPlmn: "acc_drb_pdcp_packet_drop_rate_dl_qfi_snssai_plmn"
            DRBPdcpSduDelayDlQoS: "drb_pdcp_sdu_delay_dl_qos"
            DRBPdcpSduDelayDlSnssai: "drb_pdcp_sdu_delay_dl_snssai"
            DRBPdcpSduDelayDlDistQos: "drb_pdcp_sdu_delay_dl_dist_qos"
            DRBPdcpSduDelayDlDist: "drb_pdcp_sdu_delay_dl_dist"
            DRBPdcpSduDelayDlDistSnssai: "drb_pdcp_sdu_delay_dl_dist_snssai"
            AccDRBPdcpSduDelayDlDistQfiSnssaiPlmn: "acc_drb_pdcp_sdu_delay_dl_dist_qfi_snssai_plmn"
            AccDRBEstabSucc5QiSnssai: "acc_drb_estab_succ_5qi_snssai"
            DRBEstabAttSnssai: "drb_estab_att_snssai"
            DRBEstabAtt5Qi: "drb_estab_att_5qi"
    - name: "acc_du_v3"
      component: "du"
      vendor: "accelleran"
      enabled: "true"
      consumers:
        udpConsumer:
          port: "55555"
      publishers:
        # kafkaPublisher:
        #   topic: "accelleran.drax.5g.ric.o1.ves"
        influxPublisher:
          defaultBucket: "acc_du"
          buckets:
            DUUEMeasurements: "du_ue_measurements"
            DURLCMeasurements: "du_rlc_measurements"
    - name: "cu_events"
      component: "cu"
      vendor: "accelleran"
      enabled: "true"
      consumers:
        natsConsumer:
          url: ""
          subjects: "*.F1-SCTP-ASSOC-FAILURE-IND"
      publishers:
        kafkaPublisher:
          topic: "accelleran.drax.5g.ric.o1.ves"
    - name: "grafana_alerts"
      component: "drax"
      vendor: "accelleran"
      enabled: "true"
      consumers:
        restConsumer:
          endpoint: "/alert"
          port: "9020"
      publishers:
        kafkaPublisher:
          topic: "accelleran.drax.5g.ric.o1.ves"

extraResources: []
