{{- if (.Values.auth).enabled }}
{{- $users := dict -}}
{{- range $index, $user := .Values.auth.users -}}
{{- $username := $user.username | required (printf "A username is required when auth is enabled in loki-gateway (auth.users[%d].username)" $index) -}}
{{- $password := $user.password | default (randAscii 48) -}}
{{- $_ := set $users $username $password -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loki-gateway.fullname" . }}-auth
  labels: {{- include "loki-gateway.labels" . | nindent 4 }}
  {{- if (.Values.auth).preventSecretUninstall }}
  annotations:
    helm.sh/resource-policy: "keep"
  {{- end }}
type: Opaque
stringData:
  htpasswd: |-
    {{- range $username, $password := $users }}
      {{ htpasswd $username $password }}
    {{- end }}

  {{- range $username, $password := $users }}
  {{ $username }}: {{ $password | quote }}
  {{- end }}
{{- end }}
