{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.persistence.type "pvc")}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.persistence.finalizers  }}
  finalizers:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
{{- /*
  an empty string has a special meaning for a storageClassName:
  https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass
*/ -}}
{{- if or .Values.persistence.storageClassName (eq .Values.persistence.storageClassName "") }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}
