nameOverride: ""
fullnameOverride: ""

image:
  repository: accelleran/loki-deleter
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

  pullPolicy: IfNotPresent

accelleranLicense:
  enabled: false

imagePullSecrets:
  - name: accelleran-secret

config:
  loki:
    host: ""

extraEnvs: []

annotations: {}

replicaCount: 1

resources: {}

podSecurityContext:
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001

securityContext:
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

podLabels: {}
podAnnotations: {}

affinity: {}
tolerations: []
nodeSelector: {}

extraVolumes: []
extraVolumeMounts: []
