apiVersion: v2
name: golang-nkafka
description: The Accelleran dRAX nats-kafka bridge
type: application
version: 2.0.1
appVersion: 1.3.7
dependencies:
  - name: common
    version: 0.3.8
    repository: https://accelleran.github.io/helm-charts/
