apiVersion: v2
name: golang-nkafka
description: The Accelleran dRAX nats-kafka bridge
type: application
version: 1.2.1
appVersion: 1.3.4
dependencies:
  - name: common
    version: 0.1.2
    repository: https://accelleran.github.io/helm-charts-ng/
