global:

  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

  imagePullSecrets:
    - name: accelleran-secret

  persistentLogLevel: info

  nodeSelector: {}

  accelleranLicense:
    enabled: true
    secretName: accelleran-cu-license


# Number of components
#   Description:  You have to specify the amount of different components that should be supported.
#                 Therefore, you have to specify:
#                 - the number of UP stacks that will be used, explicitly split between regular and xdp UP stacks
#                   (xdp up stacks need a list with details to determine the number of components)
numberOfUpStacks: 2
xdpUpStacks: []
# - # nodeSelector, nodeSelectorOverride and nodeName are optional, but at least one of them should probably be used
#   # Otherwise in multi-node clusters, there's no way to know which Node the XDP Pod will be assigned to
#   # and it's unlikely the interface/IP information is correct
#   # nodeSelectorOverride is similar to nodeSelector but if specified only those labels will be used for this Pod
#   nodeSelector:
#     example-label: example-value
#   nodeSelectorOverride:
#     override-label: override-value
#   nodeName: example-node-name

#   ng-u:
#     address: "127.0.0.1"
#     mtu: 1460  # optional, default 1460, only minimum MTU (compared with f1-u) is used

#   f1-u:
#     address: "127.0.0.2"
#     mtu: 1460  # optional, default 1460, only minimum MTU (compared with ng-u) is used


bootstrap:
  create: true
  name: ""

  # CU-UP Instance ID
  #   Description:  The Instance ID of the CU-UP component that
  #                 will be used in the bootstrap file.
  #                 The Instance ID must consist of lower case alphanumeric characters
  #                 or '-', start with an alphabetic character, and end with an alphanumeric
  #                 character (e.g. 'my-name',  or 'abc-123', regex used for validation is
  #                 '^[a-z0-9-]+$'). The Instance ID also cannot be longer than 19 characters!
  #
  #   Example:
  # instanceId: "cuup-1"
  #
  instanceId: "cuup-1"

  nats:
    enabled: true
    hostname: ""
    port: 0

drax:
  technology: "5g"
  role: "5g"

nameOverride: ""
fullnameOverride: ""

component: "cu-up"

natsInitImage:
  repository: accelleran/acc-generic-img
  tag: "0.9.2"
  pullPolicy: IfNotPresent

image:
  repository: accelleran/cu-up
  tag: ""
  pullPolicy: IfNotPresent

service:
  enabled: true
  name: ""
  type: "ClusterIP"
  ports:
    netconf:
      appProtocol: "netconf-ssh"
      protocol: "TCP"
      port: 8300
      targetPort: 0
      nodePort: 0

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

readinessProbe:
  exec:
    command:
      - "test"
      - "-f"
      - "/tmp/netopeer2-server.pid"
  initialDelaySeconds: 15
  periodSeconds: 30

podSecurityContext:
  fsGroup: 1000

persistence:
  - name: sysrepo
    mountPath: "/workdir/sysrepo"
    storageClassName: ""
    accessModes:
      - "ReadWriteOnce"
    size: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}


ups:
  enabled: true

  nameOverride: "ups"
  component: "ups"

  containerName: "ups"

  loadBalancerIPInitImage:
    repository: accelleran/acc-generic-img
    tag: "0.9.2"
    pullPolicy: IfNotPresent

  image:
    repository: accelleran/ups
    tag: ""
    pullPolicy: IfNotPresent

  accelleranLicense:
    enabled: false

  args:
    - "--ng-u"
    - "${NG_U}"
    - "--f1-u"
    - "${F1_U}"
    - "--bind"
    - "${BIND}"

  service:
    enabled: true
    name: ""
    type: "LoadBalancer"
    ports:
      gtp-u:
        appProtocol: "gtp-user"
        protocol: "UDP"
        port: 2152
        targetPort: 0
        nodePort: 0
    loadBalancerIP: ""
    externalTrafficPolicy: "Local"

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  rbac:
    enabled: true
    rules:
      - apiGroups:
        - ""
        resources:
        - services
        verbs:
        - get

  podSecurityContext: {}
    # fsGroup: 2000

  nodeSelector: {}

  tolerations: []

  affinity: {}


xdp-ups:
  enabled: true

  nameOverride: "xdp-ups"
  component: "xdp-ups"

  containerName: "xdp-ups"

  image:
    repository: accelleran/xdp-ups
    tag: ""
    pullPolicy: IfNotPresent

  accelleranLicense:
    enabled: false

  args:
    - "--ng-u"
    - "${NG_U}"
    - "--f1-u"
    - "${F1_U}"

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    # XDP UPS needs to run as root
    runAsUser: 0
    runAsGroup: 0
    privileged: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

nats:
  enabled: false

  natsBox:
    enabled: false

extraResources: []
