apiVersion: v2
name: xapp-hello-world
description: A Helm chart for Accelleran dRAX xApp
type: application
version: 3.0.4
# renovate: image=accelleran/xapp-framework-package
appVersion: 3.0.5
dependencies:
  - name: xapp-redis
    condition: xapp-redis.enabled
    version: 0.3.0
    repository: file://charts/xapp-redis
