{
 "title": "5G CUCP PM Counters - 5m Aggregation",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "NetworkFunctionId",
    "query": {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"RRCConnMean\") \n  |> keep(columns: [\"NetworkFunctionId\"]) \n  |> distinct(column: \"NetworkFunctionId\")\n  |> sort(columns: [\"NetworkFunctionId\"], desc: false)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RRC Connection Attempts",
   "type": "timeseries",
   "description": "This measurement provides the number of RRC connection establishment attempts for each establishment cause.",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"RRCConnEstabAtt\") and\n    r._field == \"Value\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NetworkFunctionId\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n    |> map(fn: (r) => ({\n      _time: r._time,\n      NetworkFunctionId:r.NetworkFunctionId,\n      \"Id\": r.RRCConnEstabAtt\n  }))\n  |> keep(columns: [\"_time\", \"Id\", \"NetworkFunctionId\"])\n\n"
    }
   ]
  },
  {
   "title": "RRC Connection Success Rate ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"RRCConnEstabSucc\" or r._measurement == \"RRCConnEstabAtt\") and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NetworkFunctionId\", \"_measurement\"])\n  |> sum(column: \"_value\")\n  |> pivot(rowKey: [\"NetworkFunctionId\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      NetworkFunctionId: r.NetworkFunctionId,\n      RRCConnSuccessRate: float(v: r.RRCConnEstabSucc ) / float(v: r.RRCConnEstabAtt) *100.0  }))\n  |> group() \n  |> mean(column: \"RRCConnSuccessRate\")\n  |> yield(name: \"RRC Connection Success Rate\")"
    }
   ]
  },
  {
   "title": "Number of DRBs attempted to setup ",
   "type": "timeseries",
   "description": "This measurement provides the number of DRBs attempted to setup to support all requested QoS flows in the PDU sessions to be setup by the INITIAL CONTEXT SETUP REQUESTs, PDU SESSION RESOURCE\nSETUP REQUESTs and PDU SESSION RESOURCE MODIFY REQUEST message received by the gNB from AMF. This measurement is split into subcounters per mapped 5QI and per S-NSSAI.",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"radio_resource_utilization_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"AccDRBEstabAtt5QiSnssai\") and\n    r._field == \"Value\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NetworkFunctionId\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n    |> map(fn: (r) => ({\n      _time: r._time,\n      NetworkFunctionId:r.NetworkFunctionId,\n      \"Id\": r.AccDRBEstabAtt5QiSnssai\n  }))\n  |> keep(columns: [\"_time\", \"Id\", \"NetworkFunctionId\"])\n\n"
    }
   ]
  },
  {
   "title": "DRB Setup Success Rate ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"radio_resource_utilization_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"AccDRBEstabSucc5QiSnssai\" or r._measurement == \"AccDRBEstabAtt5QiSnssai\") and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NetworkFunctionId\", \"_measurement\"])\n  |> sum(column: \"_value\")\n  |> pivot(rowKey: [\"NetworkFunctionId\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      NetworkFunctionId: r.NetworkFunctionId,\n      DRBSetupSuccessRate: float(v: r.AccDRBEstabSucc5QiSnssai ) / float(v: r.AccDRBEstabAtt5QiSnssai) *100.0  }))\n  |> group() \n  |> mean(column: \"DRBSetupSuccessRate\")\n  |> yield(name: \"DRB Setup Success Rate\")"
    }
   ]
  },
  {
   "title": "INTRA GNB Handover Executions",
   "type": "timeseries",
   "description": "Intra gNB counter incremented at both intra and inter DU handover. Incremented by one at sending of RRC Reconfiguration message to initiate the handover in the UE",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"handover_and_mobility_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"MMHoExeIntraReq\") and\n    r._field == \"Value\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NetworkFunctionId\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n    |> map(fn: (r) => ({\n      _time: r._time,\n      NetworkFunctionId:r.NetworkFunctionId,\n      \"Id:\": r.MMHoExeIntraReq\n  }))\n  |> keep(columns: [\"_time\", \"Id:\", \"NetworkFunctionId\"])\n\n"
    }
   ]
  },
  {
   "title": "INTRA GNB Handover Execution Success Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"handover_and_mobility_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    (r._measurement == \"MMHoExeIntraSucc\" or r._measurement == \"MMHoExeIntraReq\") and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NetworkFunctionId\", \"_measurement\"])\n  |> sum(column: \"_value\")\n  |> pivot(rowKey: [\"NetworkFunctionId\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      NetworkFunctionId: r.NetworkFunctionId,\n      MMHoExeIntraSuccessRate: float(v: r.MMHoExeIntraSucc ) / float(v: r.MMHoExeIntraReq) *100.0  }))\n  |> group() \n  |> mean(column: \"MMHoExeIntraSuccessRate\")\n  |> yield(name: \"HO Execution Success Rate\")"
    }
   ]
  },
  { "title": "RRC Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Mean Number of RRC Connections",
   "type": "bargauge",
   "description": "This measurement provides the mean number of users in RRC connected mode during each granularity period. This measurement is obtained by sampling at a pre-defined interval, the number of users in RRC connected\nmode for each NR cell and then taking the arithmetic mean.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnMean\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"]) \n  |> last(column: \"_value\") \n  |> map(fn: (r) => ({\n      \"NR Cell ID:\": r._value,\n      NrCellId: r.NrCellId \n  }))\n  |> keep(columns: [\"NR Cell ID:\", \"NrCellId\"]) \n"
    }
   ]
  },
  {
   "title": "Max Number of RRC Connections",
   "type": "bargauge",
   "description": "This measurement provides the maximum number of users in RRC connected mode during each granularity period. This measurement is obtained by sampling at a pre-defined interval, the number of users in RRC connected mode for each NR cell and then taking the maximum.",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnMax\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"]) \n  |> last(column: \"_value\") \n  |> map(fn: (r) => ({\n      \"NR Cell ID:\": r._value,\n      NrCellId: r.NrCellId \n  }))\n  |> keep(columns: [\"NR Cell ID:\", \"NrCellId\"]) \n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "RRC Connection Establishment Attempts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => \n  r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and  \n  r._field == \"Value\"\n  )\n  |> group(columns: [\"NetworkFunctionId\"])\n|> map(fn: (r) => ({\n      r with\n      \"Id:\": r._value\n  }))\n|> keep(columns: [\"_time\", \"NetworkFunctionId\", \"Id:\"])\n"
    }
   ]
  },
  {
   "title": "RRC Connection Establishment Attempts ",
   "type": "stat",
   "description": "This measurement provides the number of RRC connection establishment attempts for each establishment cause.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts\")\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 31 },
   "options": {
    "content": "<h4 style=\"text-align:center\">RRC Connection Establishment Attempt <h4>\n<h4 style=\"text-align:center\"> cause sub-counters <h4>\n"
   }
  },
  {
   "title": "EMERGENCY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_EMERGENCY\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - Emergency Cause\")\n"
    }
   ]
  },
  {
   "title": "MT_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MT_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MT Access\")\n"
    }
   ]
  },
  {
   "title": "MO_DATA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_DATA\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MO Data\")\n"
    }
   ]
  },
  {
   "title": "MO_SMS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_SMS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MO SMS\")\n"
    }
   ]
  },
  {
   "title": "MCS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MCS_PRIORITY_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MCS Priority Access\")\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "HIGH_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_HIGH_PRIORITY_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - High Priotity Access\")\n"
    }
   ]
  },
  {
   "title": "MO_SIGNALLING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_SIGNALLING\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MO Signalling\")\n"
    }
   ]
  },
  {
   "title": "MO_VOICE_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_VOICE_CALL\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MO Voice Call\")\n"
    }
   ]
  },
  {
   "title": "MO_VIDEO_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_VIDEO_CALL\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MO Video Call\")\n"
    }
   ]
  },
  {
   "title": "MPS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MPS_PRIORITY_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Attempts - MPS Priority Access\")\n"
    }
   ]
  },
  {
   "title": "RRC Connection Successes",
   "type": "stat",
   "description": "This measurement provides the number of successful RRC establishments for each establishment cause",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes\")\n"
    }
   ]
  },
  {
   "title": "RRC CONNECTION SUCCESSES",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => \n  r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n  r._field == \"Value\"\n  )\n  |> group(columns: [\"NetworkFunctionId\"])\n|> map(fn: (r) => ({\n      r with\n      \"Id:\": r._value\n  }))\n|> keep(columns: [\"_time\", \"NetworkFunctionId\", \"Id:\"])\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 47 },
   "options": {
    "content": "<h4 style=\"text-align:center\">RRC Connection Success <h4>\n<h4 style=\"text-align:center\"> cause sub-counters <h4>\n"
   }
  },
  {
   "title": "EMERGENCY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_EMERGENCY\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - Emergency Cause\")\n"
    }
   ]
  },
  {
   "title": "MO_SIGNALLING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_SIGNALLING\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MO Signalling\")\n"
    }
   ]
  },
  {
   "title": "MO_VOICE_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_VOICE_CALL\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MO Voice Call\")\n"
    }
   ]
  },
  {
   "title": "MO_SMS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_SMS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MO SMS\")\n"
    }
   ]
  },
  {
   "title": "MPS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MPS_PRIORITY_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MPS Priority Access\")\n"
    }
   ]
  },
  {
   "title": "HIGH_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_HIGH_PRIORITY_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - High Priotity Access\")\n"
    }
   ]
  },
  {
   "title": "MT_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MT_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MT Access\")\n"
    }
   ]
  },
  {
   "title": "MO_DATA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_DATA\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MO Data\")\n"
    }
   ]
  },
  {
   "title": "MO_VIDEO_CALL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MO_VIDEO_CALL\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MO Video Call\")\n"
    }
   ]
  },
  {
   "title": "MCS_PRIORITY_ACCESS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnEstabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    ) and\n    r.CauseType == \"CAUSE_TYPE_MCS_PRIORITY_ACCESS\"\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Establishment Successes - MCS Priority Access\")\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 56 },
   "options": {
    "content": "<h4 style=\"text-align:center\">RRC Re-establishment Counters <h4>"
   }
  },
  {
   "title": "RRC Re-establishment Attempts",
   "type": "stat",
   "description": "This measurement provides the number of RRC connection re-establishment attempts",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnReestabAtt\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Connection Re-stablishment Attempts\")\n"
    }
   ]
  },
  {
   "title": "RRC Re-establishment Successes",
   "type": "stat",
   "description": "This measurement provides the successful number of RRC connection re-establishments",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"rrc_connection_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"RRCConnReestabSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"RRC Re-establishment Successes\")\n"
    }
   ]
  },
  {
   "title": "Handover Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "INTRA gNB Handover Executions",
     "type": "stat",
     "description": "Intra gNB counter incremented at both intra and inter DU handover. Incremented by one at sending of RRC Reconfiguration message to initiate the handover in the UE",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"handover_and_mobility_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"MMHoExeIntraReq\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"Intra Handover Executions\")\n"
      }
     ]
    },
    {
     "title": "INTRA gNB Handover Successes",
     "type": "stat",
     "description": "Intra gNB counter incremented at both intra and inter DU handover. Incremented by one on reception of RRC Reconfiguration Complete",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"handover_and_mobility_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"MMHoExeIntraSucc\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"Intra Handover Successes\")\n"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 66 } }
   ]
  },
  {
   "title": "PDU Session Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "PDU Session Setup Requests",
     "type": "stat",
     "description": "Number of PDU sessions requested to setup (28.522 section 5.1.1.5.1). CU-CP counter per NR cell. The measurement is split into subcounters per S-NSSAI\n\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"pdu_session_management_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"SMPDUSessionSetupReq\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"Number of PDU sessions requested to setup\")\n"
      }
     ]
    },
    {
     "title": "PDU Session Setup Failures",
     "type": "stat",
     "description": "This measurement provides the number of PDU Sessions failed to setup by the gNB. This measurement is split into subcounters per failure cause.",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "query": "from(bucket: \"pdu_session_management_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"SMPDUSessionSetupFail\" and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"NrCellId\", \"PlmnId\"])\n  |> sum(column: \"_value\")\n  |> group() \n  |> sum(column: \"_value\")\n  |> yield(name: \"Number of PDU sessions failed to setup\")\n"
      }
     ]
    }
   ]
  }
 ]
}