{
 "title": "5G CUUP PM Counters",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "SNSSAI",
    "query": {
     "query": "from(bucket: \"radio_resource_utilization_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"AccDRBPdcpPacketDropRateDlSnssai\") \n  |> keep(columns: [\"Snssai\"]) \n  |> distinct(column: \"Snssai\")\n  |> sort(columns: [\"Snssai\"], desc: false)\n"
    }
   },
   {
    "name": "NetworkFunctionId",
    "query": {
     "query": "from(bucket: \"throughput_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"AccGTPThpDl\") \n  |> keep(columns: [\"NetworkFunctionId\"]) \n  |> distinct(column: \"NetworkFunctionId\")\n  |> sort(columns: [\"NetworkFunctionId\"], desc: false)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DL GTP Throughput per SNSSAI",
   "type": "timeseries",
   "description": "Measure of DL GTP data received during the  reporting period in the observed cell. Data for all UEs (all PDU sessions) in a cell is aggregated",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_cuupId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "import \"strings\" \n\nfrom(bucket: \"throughput_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"AccGTPThpDlQfiSnssaiPlmn\" and\n    r._field == \"Value\"\n    and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> map(fn: (r) => ({\n      r with\n      Snssai: strings.split(v: r.QFISNSSAIPLMNID, t: \",\")[1]\n  }))\n  |> filter(fn: (r) => \n    contains(value: r.Snssai, set: ${SNSSAI:json})  )\n  |> group(columns: [\"Snssai\", \"NetworkFunctionId\"])\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      NetworkFunctionId: r.NetworkFunctionId,\n      Snssai: r.Snssai, \n      \"_value\": float(v: r._value) * 8.0\n  }))\n  |> sort(columns: [\"_time\"], desc: false) \n  |> keep(columns: [\"_time\", \"NetworkFunctionId\" ,\"Snssai\", \"_value\" ])\n",
     "select": [
      [
       { "params": [ "measurement.dlGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UL GTP Throughput per SNSSAI",
   "type": "timeseries",
   "description": "Measure of UL GTP data received during the  reporting period in the observed cell. Data for all UEs (all PDU sessions) in a cell is aggregated",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_cuupId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "import \"strings\" \n\nfrom(bucket: \"throughput_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"AccGTPThpUlQfiSnssaiPlmn\" and\n    r._field == \"Value\"\n    and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> map(fn: (r) => ({\n      r with\n      Snssai: strings.split(v: r.QFISNSSAIPLMNID, t: \",\")[1]\n  }))\n  |> filter(fn: (r) => \n    contains(value: r.Snssai, set: ${SNSSAI:json})  )\n  |> group(columns: [\"Snssai\", \"NetworkFunctionId\"])\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: true)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      NetworkFunctionId: r.NetworkFunctionId,\n      Snssai: r.Snssai, \n      \"_value\": float(v: r._value) * 8.0\n  }))\n  |> sort(columns: [\"_time\"], desc: false) \n  |> keep(columns: [\"_time\", \"NetworkFunctionId\" ,\"Snssai\", \"_value\" ])\n",
     "select": [
      [
       { "params": [ "measurement.ulGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DRB PACKET LOSS RATE UL per SNSSAI",
   "type": "timeseries",
   "description": "This measurement provides the fraction of PDCP SDU packets which are not successfully received at gNB-CU-UP. It is a measure of the UL packet loss on the F1-U interface. The measurement is optionally split into subcounters per QoS level (mapped 5QI or QCI in NR option 3) and subcounters per supported S-NSSAI.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "timestart = uint(v: v.timeRangeStart)\ntimestop = uint(v: v.timeRangeStop)\nduration = duration(v:timestop - timestart)\n\nconditionalAggregate = (tables=<-) => \n  if int(v:duration) > int(v:15m) then\n    tables\n      |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n      |> fill(usePrevious: true) \n  else\n    tables\n    \nfrom(bucket: \"radio_resource_utilization_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"AccDRBF1UPacketLossRateUlSnssai\" and\n    r._field == \"Value\" and\n    (\n      \"${SNSSAI}\" == \"All\" or r.Snssai == \"${SNSSAI}\" or contains(value: r.Snssai, set: ${SNSSAI:json})\n    ) and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> group(columns: [\"Snssai\", \"NetworkFunctionId\"])\n  |> conditionalAggregate()\n  |> map(fn: (r) => ({\n      _time: r._time,\n      NetworkFunctionId: r.NetworkFunctionId, \n      Snssai: r.Snssai, \n      \"_value\": r._value/1000000\n  }))\n  |> sort(columns: [\"_time\"], desc: false) \n  |> keep(columns: [\"_time\", \"NetworkFunctionId\" ,\"Snssai\", \"_value\" ])\n"
    }
   ]
  },
  {
   "title": "AVERAGE DELAY DL PER SNSSAI",
   "type": "stat",
   "description": "The average (arithmetic mean) PDCP SDU delay on the downlink within the gNB-CU-UP for all PDCP packets in ms",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"radio_resource_utilization_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => \n    r._measurement == \"DRBPdcpSduDelayDlSnssai\"  \n    and\n    (\n      \"${SNSSAI}\" == \"All\" or r.Snssai == \"${SNSSAI}\" or contains(value: r.Snssai, set: ${SNSSAI:json})\n    ) and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n  )\n  |> map(fn: (r) => ({ r with \"Snssai:\": float(v: r._value) * 0.1 }))\n  |> group(columns: [\"Snssai\"])\n  |> mean(column: \"Snssai:\")\n"
    }
   ]
  },
  {
   "title": "Distribution of delay DL in CU-UP",
   "type": "bargauge",
   "description": "The distribution of PDCP SDU delay on the downlink within the gNB-CU-UP, for all PDCP packets (time when sending a PDCP SDU to the gNB-DU at the egress PDCP layer on F1-U/Xn-U, minus time of arrival of the same packet at NG-U ingress IP termination) distributed in following bins\n\n| bin  | value |\n| - | - | \n|bin0 | <= 5ms |\n|bin1 | 6ms to 10ms |\n|bin2 | 11ms to 20ms |\n|bin3 | 21ms to 30ms |\n|... | ... |\n|bin10 | 91ms to 100ms |\n|bin11 | 101ms to 200ms |\n|bin12 | 201ms to 300ms |\n|... |\t... |\n|bin19 | 901ms to 1000ms |\n|bin20 | >1s to <=2s |\n|bin21 | >2s to <=3s |\n|bin22 | >3s to <=4s |\n|bin23 | >4s to <=5s |\n|bin24 | > 5s |",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"radio_resource_utilization_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"DRBPdcpSduDelayDlDistSnssai\" and\n    (\n      \"${SNSSAI}\" == \"All\" or r.Snssai == \"${SNSSAI}\" or contains(value: r.Snssai, set: ${SNSSAI:json})\n    ) and\n    (\n      \"${NetworkFunctionId}\" == \"All\" or r.NetworkFunctionId == \"${NetworkFunctionId}\" or contains(value: r.NetworkFunctionId, set: ${NetworkFunctionId:json})\n    )\n    )\n  |> group(columns: [\"BinX\"]) \n  |> sum(column: \"_value\") \n    |> map(fn: (r) => ({\n      \"Bin:\": r._value,\n      BinX: r.BinX \n  }))\n"
    }
   ]
  }
 ]
}