{
 "title": "DU Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "AggregationTime", "query": "1s,5s,15s,30s,1m,15m,30m,1h" },
   { "name": "bucket", "query": "default" },
   {
    "name": "PCI",
    "query": {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"ue_info\") \n  |> keep(columns: [\"pci\"]) \n  |> distinct(column: \"pci\")\n  |> sort(columns: [\"pci\"], desc: false)"
    }
   },
   {
    "name": "RNTI",
    "query": {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"ue_info\") \n  |> keep(columns: [\"rnti\"]) \n  |> distinct(column: \"rnti\")\n  |> sort(columns: [\"rnti\"], desc: false)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align:center\"><img src=\"https://firecell.io/wp-content/uploads/2022/03/Logo-Firecell-SVG.svg\" />"
   }
  },
  {
   "title": "Active UEs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => \n      r[\"_measurement\"] == \"ue_info\" and \n      r[\"testbed\"] == \"default\" and\n      r[\"_field\"] == \"dl_brate\" and\n      ( (r[\"pci\"] == \"${PCI}\") or (contains(value: r.pci, set: ${PCI:json})) )\n    )\n  |> map(fn: (r) => ({ r with ue_id: r[\"pci\"]+\".\"+r[\"rnti\"]}))\n  |> window(every: ${AggregationTime})\n  |> group(columns: [\"_stop\"])\n  |> unique(column: \"ue_id\")\n  |> count(column: \"ue_id\")\n  |> map(fn: (r) => ({ r with _value: r[\"ue_id\"] }))\n  |> keep(columns: [\"_value\"])\n"
    }
   ]
  },
  {
   "title": "Current Total Downlink Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_brate\"\n  )\n  |> drop(columns: [\"rnti\"])\n  |> drop(columns: [\"pci\"])\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> map(fn: (r) => ({\n      r with \n      _value: float(v: r._value) / (float(v: int(v: duration(v: \"${AggregationTime}\"))) / 1000000000.0)\n  }))\n\n"
    }
   ]
  },
  {
   "title": "Maximum Total Downlink Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_brate\"\n  )\n  |> drop(columns: [\"rnti\"])\n  |> drop(columns: [\"pci\"])\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> map(fn: (r) => ({\n      r with \n      _value: float(v: r._value) / (float(v: int(v: duration(v: \"${AggregationTime}\"))) / 1000000000.0)\n  }))\n\n"
    }
   ]
  },
  {
   "title": "Current Total Uplink Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ul_brate\"\n  )\n  |> drop(columns: [\"rnti\"])\n  |> drop(columns: [\"pci\"])\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> map(fn: (r) => ({\n      r with \n      _value: float(v: r._value) / (float(v: int(v: duration(v: \"${AggregationTime}\"))) / 1000000000.0)\n  }))\n\n"
    }
   ]
  },
  {
   "title": "Maximum Total Uplink Bitrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ul_brate\"\n  )\n  |> drop(columns: [\"rnti\"])\n  |> drop(columns: [\"pci\"])\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> map(fn: (r) => ({\n      r with \n      _value: float(v: r._value) / (float(v: int(v: duration(v: \"${AggregationTime}\"))) / 1000000000.0)\n  }))\n\n"
    }
   ]
  },
  {
   "title": "Downlink Bitrate",
   "type": "timeseries",
   "description": "DRB.UEThpDl*",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_brate\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
    }
   ]
  },
  {
   "title": "Uplink Bitrate",
   "type": "timeseries",
   "description": "DRB.UEThpUl*",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ul_brate\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
    }
   ]
  },
  {
   "title": "Downlink PRBs Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"mean_pdsch_prbs_used\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
    }
   ]
  },
  {
   "title": "Uplink PRBs Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"mean_pusch_prbs_used\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
    }
   ]
  },
  {
   "title": "Downlink MCS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_mcs\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
    }
   ]
  },
  {
   "title": "Uplink MCS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ul_mcs\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"cqi\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
    }
   ]
  },
  {
   "title": "Uplink SNR (PUSCH)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"pusch_snr_db\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )\n"
    }
   ]
  },
  {
   "title": "UE Metrics - Extra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "DL Retransmission %",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "query": "data_nok = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_nof_nok\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> keep(columns: [\"_time\", \"pci\", \"rnti\", \"_value\"])\n\ndata_ok = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_nof_ok\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> keep(columns: [\"_time\", \"pci\", \"rnti\", \"_value\"])\n\n\njoin(\n  tables: {nok: data_nok, ok: data_ok},\n  on: [\"_time\", \"pci\", \"rnti\"]\n)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )\n  |> map(fn: (r) => ({ r with ratio: float(v: r._value_nok) / (float(v: r._value_ok) + float(v: r._value_nok)) }))\n  |> keep(columns: [\"_time\", \"ratio\", \"pci\", \"rnti\"])\n"
      }
     ]
    },
    {
     "title": "UL Retransmission %",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "query": "data_nok = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ul_nof_nok\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> keep(columns: [\"_time\", \"pci\", \"rnti\", \"_value\"])\n\ndata_ok = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ul_nof_ok\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: sum)\n  |> keep(columns: [\"_time\", \"pci\", \"rnti\", \"_value\"])\n\n\njoin(\n  tables: {nok: data_nok, ok: data_ok},\n  on: [\"_time\", \"pci\", \"rnti\"]\n)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )\n  |> map(fn: (r) => ({ r with ratio: float(v: r._value_nok) / (float(v: r._value_ok) + float(v: r._value_nok)) }))\n  |> keep(columns: [\"_time\", \"ratio\", \"pci\", \"rnti\"])\n"
      }
     ]
    },
    {
     "title": "DL Rank Indicator",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_ri\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )\n"
      }
     ]
    },
    {
     "title": "UL Rank Indicator",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ul_ri\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )\n"
      }
     ]
    },
    {
     "title": "Timing Advance",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"ta_ns\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
      }
     ]
    },
    {
     "title": "Power Headroom",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"last_phr\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
      }
     ]
    },
    {
     "title": "DL Buffer Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"dl_bs\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
      }
     ]
    },
    {
     "title": "Uplink RSRP (PUSCH)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "dBFS" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"pusch_rsrp_db\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
      }
     ]
    },
    {
     "title": "Buffer Status Report",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"bsr\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
      }
     ]
    },
    {
     "title": "Uplink SNR (PUCCH)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n    r[\"_measurement\"] == \"ue_info\" and \n    r[\"testbed\"] == \"default\" and\n    r[\"_field\"] == \"pucch_snr_db\"\n  )\n  |> aggregateWindow(every: ${AggregationTime}, fn: mean)\n  |> filter(fn: (r) => \n    contains(value: r.rnti, set: ${RNTI:json}) and\n    contains(value: r.pci, set: ${PCI:json})\n  )"
      }
     ]
    }
   ]
  }
 ]
}