{
 "title": "5G UE Monitoring - 5m Aggregation",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "UE",
    "query": {
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"RrcMeasurementReport\") \n  |> keep(columns: [\"UEID\"]) \n  |> distinct(column: \"UEID\")\n  |> sort(columns: [\"UEID\"], desc: false)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UE Radio Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "nrCellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "ueId" ], "type": "tag" },
      { "params": [ "nrCellId" ], "type": "tag" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"RrcMeasurementReport\" and r.IsServingCell == \"true\"\n  and\n    (\n      (\"${UE}\" == \"All\" or r.UEID == \"${UE}\" or contains(value: r.UEID, set: ${UE:json}))\n    )\n  )\n  |> map(fn: (r) => ({\n      r with\n      NrCellIdField: r.NrCellId,\n      UEIDField: r.UEID\n  }))\n  |> pivot(\n      rowKey: [\"_time\", \"NrCellIdField\", \"UEIDField\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> sort(columns: [\"_time\"], desc: true) \n  |> map(fn: (r) => ({ \n      r with\n      \"SSB RSRP\": float(v: r.SsbRsrp) - 157.0,\n      \"SSB RSRQ\": (float(v: r.SsbRsrq) / 2.0) - 43.0,\n      \"SSB SINR\": (float(v: r.SsbSinr) / 2.0) - 23.0\n  }))\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"_time\", \"NrCellIdField\", \"UEIDField\", \"SSB RSRP\", \"SSB RSRQ\", \"SSB SINR\"])\n",
     "select": [
      [
       { "params": [ "measurement.ssbRsrp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Number of UEs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default.ssbRsrp",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"RrcMeasurementReport\") \n  |> group(columns: [\"UEID\"])\n  |> distinct(column: \"UEID\")\n  |> group() \n  |> count(column: \"UEID\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$Cell$/" }
     ]
    }
   ]
  },
  {
   "title": "DL Throughput per UE (NG-U interface)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "ueId: $tag_ueId",
     "groupBy": [
      { "params": [ "$MinStep" ], "type": "time" },
      { "params": [ "ueId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"throughput_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"AccGTPThpDl\" and\n    r._field == \"Value\" and\n    (\n      \"${UE}\" == \"All\" or r.UEID == \"${UE}\" or contains(value: r.UEID, set: ${UE:json})\n    )\n  )\n  |> group(columns: [\"UEID\"])\n  |> map(fn: (r) => ({\n      _time: r._time,\n      UEID: r.UEID, \n      \"UE:\": float(v: r._value) * 8.0\n  }))\n  |> sort(columns: [\"_time\"], desc: false) \n  |> keep(columns: [\"_time\", \"UEID\", \"UE:\"])\n",
     "select": [
      [
       { "params": [ "measurement.dlGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB RSRP",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "nrCellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"RrcMeasurementReport\" and\n    r.IsServingCell == \"true\" and\n    r._field == \"SsbRsrp\" and\n    (\n      \"${UE}\" == \"All\" or r.UEID == \"${UE}\" or contains(value: r.UEID, set: ${UE:json})\n    )\n  )\n  |> map(fn: (r) => ({\n      r with\n      UEID: r.UEID,\n      NrCellId: r.NrCellId,\n      \"_value\": float(v: r._value) - 157.0\n  }))\n  |> keep(columns: [\"_time\", \"UEID\", \"NrCellId\", \"_value\"])",
     "select": [
      [
       { "params": [ "measurement.ssbRsrp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "UL Throughput per UE (NG-U interface)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "ueId: $tag_ueId",
     "groupBy": [
      { "params": [ "$MinStep" ], "type": "time" },
      { "params": [ "ueId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"throughput_metrics_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"AccGTPThpUl\" and\n    r._field == \"Value\" and\n    (\n      \"${UE}\" == \"All\" or r.UEID == \"${UE}\" or contains(value: r.UEID, set: ${UE:json})\n    )\n  )\n  |> group(columns: [\"UEID\"])\n  |> map(fn: (r) => ({\n      _time: r._time,\n      UEID: r.UEID, \n      \"UE:\": float(v: r._value) * 8.0\n  }))\n  |> sort(columns: [\"_time\"], desc: false) \n  |> keep(columns: [\"_time\", \"UEID\", \"UE:\"])\n",
     "select": [
      [
       { "params": [ "measurement.ulGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB SINR",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "nrcellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"RrcMeasurementReport\" and\n    r.IsServingCell == \"true\" and\n    r._field == \"SsbSinr\" and\n    (\n      \"${UE}\" == \"All\" or r.UEID == \"${UE}\" or contains(value: r.UEID, set: ${UE:json})\n    )\n  )\n  |> map(fn: (r) => ({\n      r with\n      UEID: r.UEID,\n      NrCellId: r.NrCellId,\n      \"_value\": (float(v: r._value)/2.0)-23.0 \n  }))\n  |> keep(columns: [\"_time\", \"UEID\", \"NrCellId\", \"_value\"])",
     "select": [
      [
       { "params": [ "measurement.ssbSinr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB RSRQ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "nrcellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"RrcMeasurementReport\" and\n    r._field == \"SsbRsrq\" and\n    r.IsServingCell == \"true\" and\n    (\n      \"${UE}\" == \"All\" or r.UEID == \"${UE}\" or contains(value: r.UEID, set: ${UE:json})\n    )\n  )\n  |> map(fn: (r) => ({\n      r with\n      UEID: r.UEID,\n      NrCellId: r.NrCellId,\n      \"_value\": (float(v: r._value)/2.0)-43.0 \n  }))\n  |> keep(columns: [\"_time\", \"UEID\", \"NrCellId\", \"_value\"])",
     "select": [
      [
       { "params": [ "measurement.ssbRsrq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  { "title": "Radio measurements per cell", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "SSB RSRP",
   "type": "timeseries",
   "description": "Aggregated SSB RSRP for Connected UEs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "nrCellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"RrcMeasurementReport\" and\n    r.IsServingCell == \"true\" and\n    r._field == \"SsbRsrp\"\n  )\n  |> group(columns: [\"NrCellId\"])  \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> map(fn: (r) => ({\n      r with\n      NrCellId: r.NrCellId,\n      \"NrCellId:\": float(v: r._value) - 157.0\n  }))\n  |> keep(columns: [\"_time\", \"NrCellId\", \"NrCellId:\"])",
     "select": [
      [
       { "params": [ "measurement.ssbRsrp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB SINR",
   "type": "timeseries",
   "description": "Aggregated SSB SINR for Connected UEs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "nrcellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"RrcMeasurementReport\" and\n    r.IsServingCell == \"true\" and\n    r._field == \"SsbSinr\"\n  )\n  |> group(columns: [\"NrCellId\"])  \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> map(fn: (r) => ({\n      r with\n      NrCellId: r.NrCellId,\n      \"NrCellId:\":  (float(v: r._value) / 2.0) - 23.0\n  }))\n  |> keep(columns: [\"_time\", \"NrCellId\", \"NrCellId:\"])",
     "select": [
      [
       { "params": [ "measurement.ssbSinr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB RSRQ",
   "type": "timeseries",
   "description": "Aggregated SSB RSRQ for Connected UEs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "nrcellId: $tag_nrCellId",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "nrCellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "from(bucket: \"rrc_measurements_5m\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"RrcMeasurementReport\" and\n    r.IsServingCell == \"true\" and\n    r._field == \"SsbRsrq\"\n  )\n  |> group(columns: [\"NrCellId\"])  \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\n  |> map(fn: (r) => ({\n      r with\n      NrCellId: r.NrCellId,\n      \"NrCellId:\": (float(v: r._value)/2.0)-43.0 \n  }))\n  |> keep(columns: [\"_time\", \"NrCellId\", \"NrCellId:\"])",
     "select": [
      [
       { "params": [ "measurement.ssbRsrq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nrCellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  }
 ]
}