{{- if ($.Values.auth).enabled }}
{{-
  include
    "accelleran.common.secret"
    (fromYaml (include "accelleran.loki-gateway.secretAuth.args" $))
-}}
{{- end }}


{{- define "accelleran.loki-gateway.secretAuth.args" -}}
{{- $ := . -}}

{{- $name := printf "%s-auth" (include "accelleran.common.fullname" (dict "top" $)) -}}

{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $name -}}

{{- $users := dict -}}
{{- range $index, $user := $.Values.auth.users -}}
{{- $username := $user.username | required (printf "A username is required when auth is enabled in loki-gateway (auth.users[%d].username)" $index) -}}
{{- $existingPassword := get ($existingSecret.data) $username | b64dec -}}
{{- $userPassword := $user.password -}}
{{- $password := "" -}}
{{- if $.Values.auth.overwriteExistingPasswords -}}
{{- $password = $userPassword | default $existingPassword | default (randAlphaNum 48) -}}
{{- else -}}
{{- $password = $existingPassword | default $userPassword | default (randAlphaNum 48) -}}
{{- end -}}
{{- $_ := set $users $username $password -}}
{{- end -}}

top: {{ $ | toYaml | nindent 2 }}

name: {{ $name | quote }}

{{- if ($.Values.auth).preventSecretUninstall }}
annotations:
  {{- with $.Values.annotations }}
  {{ . | toYaml | nindent 2 }}
  {{- end }}
  helm.sh/resource-policy: "keep"
{{- end }}

stringData:
  htpasswd: |-
    {{- range $username, $password := $users }}
    {{ htpasswd $username $password }}
    {{- end }}

  {{- range $username, $password := $users }}
  {{ $username }}: {{ $password | quote }}
  {{- end }}
{{- end -}}
