{{- if ($.Values.auth).enabled }}
{{-
  include
    "accelleran.common.secret"
    (fromYaml (include "accelleran.loki-gateway.secretAuth.args" $))
-}}
{{- end }}


{{- define "accelleran.loki-gateway.secretAuth.args" -}}
{{- $ := . -}}

{{- $users := dict -}}
{{- range $index, $user := $.Values.auth.users -}}
{{- $username := $user.username | required (printf "A username is required when auth is enabled in loki-gateway (auth.users[%d].username)" $index) -}}
{{- $password := $user.password | default (randAscii 48) -}}
{{- $_ := set $users $username $password -}}
{{- end -}}

top: {{ $ | toYaml | nindent 2 }}

name: "{{ include "accelleran.common.fullname" (dict "top" $) }}-auth"

{{- if ($.Values.auth).preventSecretUninstall }}
annotations:
  {{- with $.Values.annotations }}
  {{ . | toYaml | nindent 2 }}
  {{- end }}
  helm.sh/resource-policy: "keep"
{{- end }}

stringData:
  htpasswd: |-
    {{- range $username, $password := $users }}
    {{ htpasswd $username $password }}
    {{- end }}

  {{- range $username, $password := $users }}
  {{ $username }}: {{ $password | quote }}
  {{- end }}
{{- end -}}
