{{- include
      "accelleran.common.deployment"
      (fromYaml (include "accelleran.cu-cp.deployment.args" .))
-}}


{{- define "accelleran.cu-cp.deployment.args" -}}
{{- $ := . -}}
{{- $values := (index $.Values "cu-cp") -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ $values | toYaml | nindent 2 }}

initContainers:
- {{ fromYaml (include "accelleran.common.init.redis" (fromYaml (include "accelleran.cu-cp.init.args" .))) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.common.init.nats" (fromYaml (include "accelleran.cu-cp.init.args" .))) | toYaml | nindent 2 }}

containers:
- {{ fromYaml (include "accelleran.cu-cp.gnb-ctrl.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.netconf.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.amf-ctrl.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.cu-up-ctrl.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.du-ctrl.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.pm-ctrl.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.res-mgr.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.sctp-ng.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.sctp-e1.container" $) | toYaml | nindent 2 }}
- {{ fromYaml (include "accelleran.cu-cp.sctp-f1.container" $) | toYaml | nindent 2 }}
{{- end -}}


{{- define "accelleran.cu-cp.init.args" -}}
{{- $ := . -}}
{{- $values := (index $.Values "cu-cp") -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ $values | toYaml | nindent 2 }}

bootstrapConfigMapName: {{ include "accelleran.common.bootstrap.configMapName" (dict "top" $) | quote }}
{{- end -}}
