{{- include
      "accelleran.common.service"
      (dict
        "top" $
        "values" (mergeOverwrite
          (deepCopy (index $.Values "cu-cp"))
          (dict "service" $.Values.netconf.service)
          (dict "service" (dict "name" (include "accelleran.cu-cp.netconf.service.name" .)))
        )
      )
-}}
