{{- include
      "accelleran.common.statefulset"
      (fromYaml (include "accelleran.cu-cp.netconf.statefulset.args" .))
-}}


{{- define "accelleran.cu-cp.netconf.statefulset.args" -}}
{{- $ := . -}}
{{- $values := (index $.Values "netconf") -}}
{{- $mergedValues := mergeOverwrite
                      (deepCopy $values)
                      (dict "nameOverride" (index $.Values "cu-cp" "nameOverride"))
-}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ $mergedValues | toYaml | nindent 2 }}

name: {{ include "accelleran.common.fullname" (dict "top" $ "values" $values) | quote }}
selectorLabels:
  {{ include "accelleran.common.selectorLabels" (dict "top" $ "values" $mergedValues) | nindent 2 }}
  app.kubernetes.io/component: {{ $values.component }}
labels:
  {{ include "accelleran.common.labels" (dict "top" $ "values" $mergedValues) | nindent 2 }}

initContainers:
- {{ fromYaml (include "accelleran.common.init.nats" (fromYaml (include "accelleran.cu-cp.netconf.init.args" .))) | toYaml | nindent 2 }}

env:
  - name: __APPNAME
    value: cuCpNetconf
{{- with (include "accelleran.common.bootstrap.instanceId" (dict "top" $)) }}
  - name: INSTANCE_FILTER
    value: {{ . | quote }}
{{- end }}
envFrom:
  - configMapRef:
      name: {{ include "accelleran.common.bootstrap.configMapName" (dict "top" $) | quote }}
{{- end -}}


{{- define "accelleran.cu-cp.netconf.init.args" -}}
{{- $ := . -}}
{{- $values := (index $.Values "netconf") -}}

top:
  {{ $ | toYaml | nindent 2 }}
values:
  {{ omit $values "readinessProbe" | toYaml | nindent 2 }}

bootstrapConfigMapName: {{ include "accelleran.common.bootstrap.configMapName" (dict "top" $) | quote }}
{{- end -}}
