apiVersion: v2
name: config-api
description: Backend of the Accelleran Dashboard
type: application
version: 3.0.0
# renovate: image=accelleran/config-api
appVersion: 2.1.2
dependencies:
  - name: common
    version: 0.5.0
    repository: https://accelleran.github.io/helm-charts/
