{{- include
      "accelleran.common.configMap"
      (fromYaml (include "accelleran.service-orchestrator.configMap.args" .))
-}}

{{- define "accelleran.service-orchestrator.configMap.args" -}}
{{- $ := . -}}

{{- $config := .Values.config }}
{{- $instance := include "accelleran.common.instance" (dict "top" .) }}

{{- if empty $config.serviceMonitorUrl }}
  {{- $config = merge $config (dict "serviceMonitorUrl" (printf "http://%s-service-monitor:80" $instance)) }}
{{- end }}

top:
  {{ $ | toYaml | nindent 2 }}

name: {{ include "accelleran.common.fullname" (dict "top" $) }}-config

data:
  config.json: |-
    {{ .Values.config | toPrettyJson | nindent 4 }}
{{- end -}}

