{{- include
      "accelleran.common.configMap"
      (fromYaml (include "accelleran.service-orchestrator.configMap.args" .))
-}}

{{- define "accelleran.service-orchestrator.configMap.args" -}}
{{- $ := . -}}

top:
  {{ $ | toYaml | nindent 2 }}

name: {{ include "accelleran.common.fullname" (dict "top" $) }}-config

data:
  config.json: |-
    {{ .Values.config | toPrettyJson | nindent 4 }}
{{- end -}}

