{
 "title": "5G CUUP PM Counters",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sliceType",
    "query": "label_values(DRB_PACKET_LOSS_UL_SNSSAI,sst)"
   },
   {
    "name": "sliceDifferentiator",
    "query": "label_values(DRB_PACKET_LOSS_UL_SNSSAI,sd)"
   },
   {
    "name": "QFI",
    "query": "label_values(DRB_PACKET_LOSS_UL_QOS,qfi)"
   },
   { "name": "MinStep", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "DL GTP Throughput",
   "type": "graph",
   "description": "Measure of DL GTP data received during the  reporting period in the observed cell. Data for all UEs (all PDU sessions) in a cell is aggregated",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Average throughput",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "SELECT mean(\"measurement.dlGtpThroughput\") *8 FROM \"uemeasurement.vector\" $timeFilter GROUP BY time(1s) ",
     "select": [
      [
       { "params": [ "measurement.dlGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UL GTP Throughput",
   "type": "graph",
   "description": "Measure of UL GTP data received during the  reporting period in the observed cell. Data for all UEs (all PDU sessions) in a cell is aggregated",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Average throughput",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "uemeasurement.vector",
     "query": "SELECT mean(\"measurement.dlGtpThroughput\") *8 FROM \"uemeasurement.vector\" $timeFilter GROUP BY time(1s) ",
     "select": [
      [
       { "params": [ "measurement.ulGtpThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DRB PDCP PACKET DROP RATE DL PER SNSSAI",
   "type": "graph",
   "description": "The fraction of PDCP SDU packets which are dropped on the downlink, due to high traffic load, traffic management etc",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "increase(DRB_PDCP_PACKET_DROP_RATE_DL_SNSSAI {} [$__rate_interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "DRB PDCP PACKET DROP RATE DL PER QFI",
   "type": "graph",
   "description": "The fraction of PDCP SDU packets which are dropped on the downlink, due to high traffic load, traffic management etc",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "increase(DRB_PDCP_PACKET_DROP_RATE_DL_QOS {qfi=~\"$QFI\"} [$__interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "AVERAGE DELAY DL PER SNSSAI",
   "type": "stat",
   "description": "The average (arithmetic mean) PDCP SDU delay on the downlink within the gNB-CU-UP for all PDCP packets",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(AVERAGE_DELAY_DL_IN_CUUP_SNSSAI{sd=~\"$sliceDifferentiator\",sst=~\"$sliceType\"}[$__interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "title": "Distribution of delay DL in CU-UP",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 18, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_0_total[$__range]))",
     "legendFormat": "0"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_1_total[$__range])) or vector(0) ",
     "legendFormat": "1"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_2_total[$__range])) or vector(0) ",
     "legendFormat": "2"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_3_total[$__range])) or vector(0) ",
     "legendFormat": "3"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_4_total[$__range])) or vector(0) ",
     "legendFormat": "4"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_5_total[$__range])) or vector(0) ",
     "legendFormat": "5"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_6_total[$__range])) or vector(0) ",
     "legendFormat": "6"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_7_total[$__range])) or vector(0) ",
     "legendFormat": "7"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_8_total[$__range])) or vector(0) ",
     "legendFormat": "8"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_9_total[$__range])) or vector(0) ",
     "legendFormat": "9"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_10_total[$__range])) or vector(0) ",
     "legendFormat": "10"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_11_total[$__range])) or vector(0) ",
     "legendFormat": "11"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_12_total[$__range])) or vector(0) ",
     "legendFormat": "12"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_13_total[$__range])) or vector(0) ",
     "legendFormat": "13"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_14_total[$__range])) or vector(0) ",
     "legendFormat": "14"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_15_total[$__range])) or vector(0) ",
     "legendFormat": "15"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_16_total[$__range])) or vector(0) ",
     "legendFormat": "16"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_17_total[$__range])) or vector(0) ",
     "legendFormat": "17"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_18_total[$__range])) or vector(0) ",
     "legendFormat": "18"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_19_total[$__range])) or vector(0) ",
     "legendFormat": "19"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_20_total[$__range])) or vector(0) ",
     "legendFormat": "20"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_21_total[$__range])) or vector(0) ",
     "legendFormat": "21"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_22_total[$__range])) or vector(0) ",
     "legendFormat": "22"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_23_total[$__range])) or vector(0) ",
     "legendFormat": "23"
    },
    {
     "expr": "sum(increase(DISTRIBUTION_OF_DELAY_DL_IN_CUUP_QOS_bin_24_total[$__range])) or vector(0) ",
     "legendFormat": "24"
    }
   ]
  },
  {
   "title": "AVERAGE DELAY DL PER QFI",
   "type": "stat",
   "description": "The average (arithmetic mean) PDCP SDU delay on the downlink within the gNB-CU-UP for all PDCP packets",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(AVERAGE_DELAY_DL_IN_CUUP_QOS{qfi=~\"$QFI\"}[$__interval])",
     "legendFormat": "{{instanceId}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<h4 style=\"text-align:center\"> <h4>\n<h4 style=\"text-align:center\"> <h4>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<h4 style=\"text-align:center\"> <h4>\n<h4 style=\"text-align:center\"> <h4>\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 0, "y": 41 } }
 ]
}