{
 "title": "Accelleran dRAX 5G System Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{node=~\"^$Node$\", pod=~\".*5g.*\"}, pod)"
   },
   {
    "name": "Pod_ip",
    "query": "label_values(kube_pod_info{pod=\"$Pod\", node=\"$Node\"}, pod_ip)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{pod=\"$Pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_node_labels)" }
   ]
  },
  {
   "title": "Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Allocatable RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Pending or Crashed Pods and Containers",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\",pod=~\".*5g.*\"} == 1"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kube_pod_labels) by (pod))"
    }
   ]
  },
  {
   "title": "Pending Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\"} == 1)"
    }
   ]
  },
  {
   "title": "Crashed Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{pod=~\"$Pod\"})"
    }
   ]
  },
  { "title": "Deployed CU Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Number of CU-CPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*sctp.*\",container=\"sctp-e1\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "Number of CU-UPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*cu-up.*\", container=~\".*netconf.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  { "title": "CU Elements Supported", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of supported UEs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*ds-ctrl.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "Number of supported DUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*f1-ap.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "Number of supported CELLS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*rr-ctrl.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "Number of supported CUUPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*e1-cp.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "Number of supported AMFs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*ng-ap.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "Number of supported UP Stacks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*ups.*\",container=~\".*ups.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  { "title": "5G Infrastructure Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*redis.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)",
     "legendFormat": "0"
    },
    {
     "expr": "(kube_pod_info{drax_role=\"5g\"})",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "Nats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*nats.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "NKafka",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*nkafka.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  { "title": "CU-CP Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "AMF Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*amf-controller.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "CU UP Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*cu-up-controller.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "DS CTRL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*ds-ctrl.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "DU Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*du-controller.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "E1 CP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*e1-cp.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "F1 AP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*f1-ap.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "GNB Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*gnb-controller.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "NG AP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*ng-ap.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "PM Controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*pm-controller.*\",container=\"pm-controller\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "RES MGR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*res-mgr.*\", container=\"res-mgr\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "RR CTRL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*rr-ctrl.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "SCTP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*sctp.*\",container=~\".*sctp.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  { "title": "CU-UP Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CU UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*cuup.*\", container=~\"pm-controller-up*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "E1 SCTP UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*e1-sctp-up.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "PM Controller UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*pm-controller.*\",container=\"pm-controller-up\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  {
   "title": "RES MGR UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\".*res-mgr-up.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1"
    }
   ]
  },
  { "title": "RAM Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes)/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Total RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Node RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\"})/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Pod RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Container RAM Usage"
    }
   ]
  },
  {
   "title": "RAM Usage History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Allocatable RAM"
    },
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Total RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Node RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\"})",
     "legendFormat": "Pod RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})",
     "legendFormat": "Container RAM Usage"
    }
   ]
  },
  {
   "title": "CPU Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(eagle_node_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Total CPU Usage"
      },
      {
       "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Node CPU Usage"
      },
      {
       "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Pod CPU Usage"
      },
      {
       "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Container CPU Usage"
      }
     ]
    },
    {
     "title": "CPU Usage History",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Allocatable CPU"
      },
      {
       "expr": "sum(eagle_node_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Total CPU Usage"
      },
      {
       "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Node CPU Usage"
      },
      {
       "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Pod CPU Usage"
      },
      {
       "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
       "legendFormat": "Container CPU Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "TX Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total[5m]))",
       "legendFormat": "Total TX Traffic"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$Node\"}[5m]))",
       "legendFormat": "Node TX Traffic"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$Node\", pod=~\"$Pod\"}[5m]))",
       "legendFormat": "Pod TX Traffic"
      }
     ]
    },
    {
     "title": "RX Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total[5m]))",
       "legendFormat": "Total RX Traffic"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$Node\"}[5m]))",
       "legendFormat": "Node RX Traffic"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$Node\", pod=~\"$Pod\"}[5m]))",
       "legendFormat": "Pod RX Traffic"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Space Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  }
 ]
}