{
 "title": "Accelleran dRAX System Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{node=~\"^$Node$\"}, pod)"
   },
   {
    "name": "Pod_ip",
    "query": "label_values(kube_pod_info{pod=\"$Pod\", node=\"$Node\"}, pod_ip)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{pod=\"$Pod\"}, container)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(kube_node_labels)" }
   ]
  },
  {
   "title": "Allocatable RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kube_pod_labels) by (pod))"
    }
   ]
  },
  {
   "title": "Pending Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\"} == 1)"
    }
   ]
  },
  {
   "title": "Crashed Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)"
    }
   ]
  },
  {
   "title": "Pending or Crashed Pods and Containers",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\"} == 1"
    },
    {
     "expr": "kube_pod_container_status_waiting == 1"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*redis.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)",
     "legendFormat": "0"
    }
   ]
  },
  {
   "title": "Nats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*nats.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "4GRC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*4g-radio-controller.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "Provisioner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "((sum(kube_pod_container_status_running{pod=~\".*provisioner.*\"}) + sum(kube_pod_container_status_running{pod=~\".*nginx.*\"})) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "Web GUI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*-dash-front-back-end.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*-influxdb.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "((sum(kube_pod_container_status_running{pod=~\".*-kafka.*\",pod!=\".*-kafka-config.*\"})+sum(kube_pod_container_status_running{pod=~\".*-zookeeper.*\"}))or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "NKafka",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*-nkafka.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_status_running{pod=~\".*-prometheus.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "((sum(kube_pod_container_status_running{pod=~\".*-kube-eagle.*\"})+sum(kube_pod_container_status_running{pod=~\".*-metrics-server.*\"})) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_status_running{pod=~\".*loki.*\"}) or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "(kube_pod_container_status_running{pod=~\".*-grafana.*\"} or kube_pod_container_status_running{pod=~\"kube-apiserver-.*\"}-1)"
    }
   ]
  },
  { "title": "RAM Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes)/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Total RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Node RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\"})/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Pod RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})/sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Container RAM Usage"
    }
   ]
  },
  {
   "title": "RAM Usage History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Allocatable RAM"
    },
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Total RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\"})",
     "legendFormat": "Node RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\"})",
     "legendFormat": "Pod RAM Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})",
     "legendFormat": "Container RAM Usage"
    }
   ]
  },
  {
   "title": "Node RAM Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(eagle_node_resource_requests_memory_bytes{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_limits_memory_bytes{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_requests_memory_bytes{node=~\"$Node\"} / eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_limits_memory_bytes{node=~\"$Node\"} / eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_usage_memory_bytes{node=~\"$Node\"} / eagle_node_resource_allocatable_memory_bytes{node=~\"$Node\"}) by (node)"
    }
   ]
  },
  {
   "title": "Pod RAM Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum (eagle_pod_container_resource_requests_memory_bytes{node=~\"$Node\", pod=~\"$Pod\"}) by (pod, node)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_limits_memory_bytes{node=~\"$Node\", pod=~\"$Pod\"}) by (pod, node)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\"}) by (pod, node)"
    }
   ]
  },
  {
   "title": "Container RAM Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "sum (eagle_pod_container_resource_requests_memory_bytes{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"}) by (node, pod, container)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_limits_memory_bytes{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"}) by (node, pod, container)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_usage_memory_bytes{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"}) by (node, pod, container)"
    }
   ]
  },
  { "title": "CPU Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(eagle_node_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Total CPU Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Node CPU Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Pod CPU Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Container CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage History",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Allocatable CPU"
    },
    {
     "expr": "sum(eagle_node_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Total CPU Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Node CPU Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Pod CPU Usage"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"})/sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"})",
     "legendFormat": "Container CPU Usage"
    }
   ]
  },
  {
   "title": "Node CPU Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "sum(eagle_node_resource_requests_cpu_cores{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_limits_cpu_cores{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_requests_cpu_cores{node=~\"$Node\"} / eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_limits_cpu_cores{node=~\"$Node\"} / eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"}) by (node)"
    },
    {
     "expr": "sum(eagle_node_resource_usage_cpu_cores{node=~\"$Node\"} / eagle_node_resource_allocatable_cpu_cores{node=~\"$Node\"}) by (node)"
    }
   ]
  },
  {
   "title": "Pod CPU Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum (eagle_pod_container_resource_requests_cpu_cores{node=~\"$Node\", pod=~\"$Pod\"}) by (node, pod)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_limits_cpu_cores{node=~\"$Node\", pod=~\"$Pod\"}) by (node, pod)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\"}) by (node, pod)"
    }
   ]
  },
  {
   "title": "Container CPU Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 36 },
   "targets": [
    {
     "expr": "sum (eagle_pod_container_resource_requests_cpu_cores{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"}) by (node, pod, container)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_limits_cpu_cores{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"}) by (node, pod, container)"
    },
    {
     "expr": "sum (eagle_pod_container_resource_usage_cpu_cores{node=~\"$Node\", pod=~\"$Pod\", container=~\"$Container\"}) by (node, pod, container)"
    }
   ]
  },
  { "title": "Network Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "TX Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[5m]))",
     "legendFormat": "Total TX Traffic"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$Node\"}[5m]))",
     "legendFormat": "Node TX Traffic"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$Node\", pod=~\"$Pod\"}[5m]))",
     "legendFormat": "Pod TX Traffic"
    }
   ]
  },
  {
   "title": "RX Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[5m]))",
     "legendFormat": "Total RX Traffic"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$Node\"}[5m]))",
     "legendFormat": "Node RX Traffic"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$Node\", pod=~\"$Pod\"}[5m]))",
     "legendFormat": "Pod RX Traffic"
    }
   ]
  },
  { "title": "Disk Space Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) /sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})"
    }
   ]
  },
  {
   "title": "Disk Usage History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname)(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"})",
     "legendFormat": "{{kubernetes_io_hostname}} - Disk Usage"
    },
    {
     "expr": "sum by (kubernetes_io_hostname)(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"})",
     "legendFormat": "{{kubernetes_io_hostname}} - Total Disk Size"
    },
    {
     "expr": "(sum by (kubernetes_io_hostname)(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}))-(sum by (kubernetes_io_hostname)(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}))",
     "legendFormat": "{{kubernetes_io_hostname}} - Available Disk Space"
    }
   ]
  },
  {
   "title": "Disk Usage per Node",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by (kubernetes_io_hostname)(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\", kubernetes_io_hostname=~\"$Node\"})",
     "legendFormat": "Node {{kubernetes_io_hostname}}"
    },
    {
     "expr": "sum by (kubernetes_io_hostname)(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\", kubernetes_io_hostname=~\"$Node\"})-sum by (kubernetes_io_hostname)(container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"$Node\"})"
    },
    {
     "expr": "sum by (kubernetes_io_hostname)(container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\", kubernetes_io_hostname=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Persistant Volumes",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by (kubernetes_node, persistentvolumeclaim) (kube_persistentvolumeclaim_info{kubernetes_node=~\"$Node\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim)(kube_persistentvolumeclaim_resource_requests_storage_bytes{kubernetes_node=~\"$Node\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kube_persistentvolumeclaim_status_phase{phase=\"Bound\",kubernetes_node=~\"$Node\"})"
    }
   ]
  }
 ]
}