{
 "title": "dRAX NATS Server Dashboard",
 "description": "NATS Server Dashboard for use with the Prometheus NATS Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nats_varz_cpu{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_cpu{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nats_varz_mem{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_mem{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nats_varz_in_bytes{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_in_bytes{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_varz_in_msgs{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_in_msgs{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nats_varz_out_bytes{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_out_bytes{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_varz_out_msgs{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_out_msgs{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_varz_connections{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_connections{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_varz_subscriptions{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_subscriptions{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nats_varz_slow_consumers{drax_technology=\"4g\"}",
     "legendFormat": "4G-NATS"
    },
    {
     "expr": "nats_varz_slow_consumers{drax_technology=\"5g\"}",
     "legendFormat": "5G-NATS"
    }
   ]
  }
 ]
}