name: Conventional Commits

on:
  push:
    branches:
      - main
      - releases/**
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:

  lint-commits:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
